import type { Metadata } from 'next'
import ScanWidget from './_components/ScanWidget'
import FaqAccordion from './_components/FaqAccordion'

export const metadata: Metadata = {
  title: 'ADA Demand Letter Response — WCAG Technical Evidence Package',
  description:
    'Received an ADA demand letter? Get a WCAG 2.2 Technical Evidence Package showing your good-faith accessibility remediation effort. Free scan, paid PDFs. Not legal advice.',
}

const FAQ = [
  {
    q: 'Does this make my website "ADA compliant"?',
    a: 'No. No automated tool can certify ADA compliance. This tool generates a Technical Evidence Package demonstrating your good-faith effort to assess and remediate accessibility issues. Whether that effort is sufficient in a specific legal context is a question for your attorney.',
  },
  {
    q: 'What does the scan cover?',
    a: "We test against WCAG 2.2 — the official standard since October 2023 and the current benchmark courts and plaintiffs reference. We use axe-core, an industry-standard open-source library by Deque Systems. Per Deque's own research across 2,000+ audits and 300,000 issues, automated scanning detects approximately 57% of WCAG issues. The remaining issues require manual testing by an accessibility specialist.",
  },
  {
    q: 'Will an accessibility widget protect me?',
    a: 'No. The FTC fined AccessiBe — one of the most popular accessibility overlay tools — $1 million in 2025 for false compliance claims. 1 in 4 ADA lawsuits in 2025 hit sites already running these widgets. Overlays do not constitute good-faith remediation effort.',
  },
  {
    q: 'How is this different from free tools?',
    a: 'Free scanners show you a list of errors and stop there. This tool produces timestamped, professionally formatted PDF documentation — an executive summary, every violation explained in plain English, and a developer remediation guide — packaged as evidence of good-faith effort you can hand directly to your attorney.',
  },
  {
    q: 'What do I get when I pay?',
    a: 'Basic ($49): the WCAG Technical Evidence Package PDF — executive summary, all violations found, legal disclaimers. Premium ($79): adds a Developer Remediation Guide with before/after code examples. Monitoring ($149/mo): adds monthly re-scans and a Monitoring Confirmation document for an ongoing evidence trail. PDFs are emailed within minutes; links valid 7 days.',
  },
  {
    q: 'Is this legal advice?',
    a: 'No. This is a technical assessment generated by automated tooling. It is not legal advice, not a compliance certification, and not a substitute for a qualified attorney. If you received an ADA demand letter, consult a licensed attorney immediately.',
  },
]

export default function HomePage() {
  const gumroadUrls = {
    basic:      process.env.GUMROAD_PRODUCT_BASIC      ?? '#',
    premium:    process.env.GUMROAD_PRODUCT_PREMIUM    ?? '#',
    monitoring: process.env.GUMROAD_PRODUCT_MONITORING ?? '#',
  }

  return (
    <main>

      {/* ── 1. Legal notice bar ───────────────────────────────────────────── */}
      <div
        className="notice-bar"
        style={{
          position: 'fixed',
          top: 0,
          left: 0,
          right: 0,
          zIndex: 200,
          height: '32px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'linear-gradient(135deg, #78350f, #92400e)',
          color: '#fef3c7',
          fontSize: '13px',
          textAlign: 'center',
          padding: '8px 16px',
          letterSpacing: '0.01em',
          whiteSpace: 'nowrap',
          overflow: 'hidden',
        }}
      >
        <span>
          ⚠ Technical assessment only — not legal advice
          <span className="notice-bar-mid"> · axe-core identifies ~57% of WCAG 2.2 issues</span>
          <span className="notice-bar-end"> · Always consult a qualified attorney</span>
        </span>
      </div>

      {/* ── 2. Navbar ─────────────────────────────────────────────────────── */}
      <nav
        style={{
          position: 'sticky',
          top: '32px',
          zIndex: 100,
          background: 'rgba(6, 9, 18, 0.85)',
          backdropFilter: 'blur(20px) saturate(180%)',
          WebkitBackdropFilter: 'blur(20px) saturate(180%)',
          borderBottom: '1px solid var(--border-subtle)',
          padding: '0 clamp(16px, 5vw, 80px)',
          height: '64px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          marginTop: '32px',
        }}
      >
        <span className="nav-brand" style={{ color: 'var(--accent)', fontSize: '18px', fontWeight: 700 }}>
          ⬡ ADA Evidence
        </span>
        <a
          href="#scan"
          className="btn-nav nav-cta"
          style={{
            background: 'var(--accent)',
            color: '#fff',
            border: 'none',
            borderRadius: 'var(--radius-md)',
            padding: '10px 20px',
            fontWeight: 600,
            cursor: 'pointer',
            fontSize: '14px',
            textDecoration: 'none',
          }}
        >
          Get Evidence Package →
        </a>
      </nav>

      {/* ── 3. Hero ───────────────────────────────────────────────────────── */}
      <section
        style={{
          position: 'relative',
          overflow: 'hidden',
          padding: 'clamp(80px, 12vh, 140px) 20px clamp(60px, 10vh, 120px)',
          textAlign: 'center',
          background:
            'radial-gradient(ellipse 120% 60% at 50% 0%, rgba(59,130,246,0.08), transparent 70%), ' +
            'repeating-linear-gradient(0deg, transparent, transparent 40px, rgba(255,255,255,0.015) 40px, rgba(255,255,255,0.015) 41px), ' +
            'repeating-linear-gradient(90deg, transparent, transparent 40px, rgba(255,255,255,0.015) 40px, rgba(255,255,255,0.015) 41px), ' +
            'var(--bg-base)',
        }}
      >
        <div
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '8px',
            marginBottom: '32px',
            background: 'var(--accent-dim)',
            border: '1px solid rgba(59,130,246,0.3)',
            borderRadius: 'var(--radius-full)',
            padding: '8px 20px',
            fontSize: '13px',
            color: 'var(--accent-bright)',
            letterSpacing: '0.05em',
            textTransform: 'uppercase',
          }}
        >
          ⚡ Received an ADA Demand Letter?
        </div>

        <h1
          className="hero-h1"
          style={{
            fontWeight: 900,
            letterSpacing: '-0.04em',
            lineHeight: 1.05,
            color: 'var(--text-primary)',
            maxWidth: '900px',
            margin: '0 auto 24px',
          }}
        >
          You Don&apos;t Have to Be Faster Than the{' '}
          <span
            style={{
              background: 'linear-gradient(135deg, var(--accent-bright), #a78bfa)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            Bear
          </span>
        </h1>

        <p
          style={{
            fontSize: 'clamp(16px, 2vw, 20px)',
            color: 'var(--text-secondary)',
            lineHeight: 1.7,
            maxWidth: '560px',
            margin: '0 auto 48px',
            fontWeight: 400,
          }}
        >
          Just faster than the other businesses he&apos;s chasing. Get timestamped
          WCAG technical evidence — the good faith documentation that resolves
          80% of demand letters.
        </p>

        <div id="scan" style={{ maxWidth: '680px', margin: '0 auto', textAlign: 'left' }}>
          <ScanWidget gumroadUrls={gumroadUrls} />
        </div>

        <div className="trust-bar" style={{ marginTop: '24px', fontSize: '13px', color: 'var(--text-muted)' }}>
          <span>✓ Free scan</span>
          <span>✓ No account required</span>
          <span>✓ PDF in minutes</span>
          <span>✓ Not legal advice</span>
        </div>
      </section>

      {/* ── 4. Stats bar ──────────────────────────────────────────────────── */}
      <section
        style={{
          background: 'var(--bg-surface)',
          borderTop: '1px solid var(--border-subtle)',
          borderBottom: '1px solid var(--border-subtle)',
          padding: '48px 20px',
        }}
      >
        <div className="stats-grid" style={{ textAlign: 'center' }}>
          <div>
            <div style={{ fontSize: '48px', fontWeight: 800, color: 'var(--accent-bright)' }}>
              35,000+
            </div>
            <div style={{ fontSize: '14px', color: 'var(--text-secondary)', marginTop: '8px' }}>
              ADA demand letters sent in 2025 alone
            </div>
          </div>
          <div>
            <div style={{ fontSize: '48px', fontWeight: 800, color: 'var(--danger)' }}>
              $5K–$20K
            </div>
            <div style={{ fontSize: '14px', color: 'var(--text-secondary)', marginTop: '8px' }}>
              Average settlement if you don&apos;t respond
            </div>
          </div>
          <div>
            <div style={{ fontSize: '48px', fontWeight: 800, color: 'var(--success)' }}>
              $49
            </div>
            <div style={{ fontSize: '14px', color: 'var(--text-secondary)', marginTop: '8px' }}>
              vs. $400+ for a first attorney consultation
            </div>
          </div>
        </div>
      </section>

      {/* ── 5. How it works ───────────────────────────────────────────────── */}
      <section style={{ padding: '80px 20px', textAlign: 'center' }}>
        <h2
          style={{
            fontSize: '36px',
            fontWeight: 800,
            letterSpacing: '-0.03em',
            margin: '0 0 12px',
          }}
        >
          How It Works
        </h2>
        <p style={{ color: 'var(--text-secondary)', margin: '0 0 48px' }}>
          Three steps. Under 5 minutes.
        </p>

        <div className="grid-3" style={{ maxWidth: '960px', margin: '0 auto' }}>
          {[
            {
              n: '1',
              title: 'Paste Your Website URL',
              body: 'Enter your business URL. Our scanner loads your live site in a secure headless browser and runs 50+ WCAG 2.2 accessibility checks.',
            },
            {
              n: '2',
              title: 'Review Your Results',
              body: 'See your accessibility score, a breakdown by severity, and the top violations — all in plain English you can share with your attorney.',
            },
            {
              n: '3',
              title: 'Download Your Evidence Package',
              body: 'Pay once. Get professionally formatted PDFs with timestamped evidence, legal disclaimers, and good-faith documentation.',
            },
          ].map(({ n, title, body }) => (
            <div
              key={n}
              className="card-step"
              style={{
                background: 'var(--bg-elevated)',
                border: '1px solid var(--border-subtle)',
                borderRadius: 'var(--radius-lg)',
                padding: '32px 24px',
                textAlign: 'left',
              }}
            >
              <div
                style={{
                  width: '36px',
                  height: '36px',
                  background: 'var(--accent-dim)',
                  border: '1px solid rgba(59,130,246,0.3)',
                  borderRadius: 'var(--radius-md)',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: '14px',
                  fontWeight: 700,
                  color: 'var(--accent-bright)',
                  marginBottom: '20px',
                }}
              >
                {n}
              </div>
              <h3 style={{ fontSize: '18px', fontWeight: 700, margin: '0 0 12px' }}>{title}</h3>
              <p style={{ fontSize: '14px', color: 'var(--text-secondary)', lineHeight: 1.6, margin: 0 }}>
                {body}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── 6. FAQ ────────────────────────────────────────────────────────── */}
      <section style={{ padding: '80px 20px', maxWidth: '760px', margin: '0 auto' }}>
        <h2
          style={{
            fontSize: '36px',
            fontWeight: 800,
            letterSpacing: '-0.03em',
            margin: '0 0 48px',
            textAlign: 'center',
          }}
        >
          Common Questions
        </h2>
        <FaqAccordion items={FAQ} />
      </section>

      {/* ── 7. Footer ─────────────────────────────────────────────────────── */}
      <footer
        className="footer-bar"
        style={{
          background: 'var(--bg-surface)',
          borderTop: '1px solid var(--border-subtle)',
          padding: '40px 20px',
        }}
      >
        <span style={{ color: 'var(--accent)', fontWeight: 700 }}>⬡ ADA Evidence Tool</span>
        <span style={{ color: 'var(--text-muted)', fontSize: '13px' }}>
          Not legal advice. Technical assessment only. © 2026
        </span>
        <span style={{ color: 'var(--text-muted)', fontSize: '12px' }}>
          axe-core ~57% WCAG 2.2 coverage
        </span>
      </footer>

    </main>
  )
}
