// Every PDF generated here MUST carry the legal disclaimer and ~57% axe-core coverage
// disclosure. CLAUDE.md Hard Rule 5 & 6 — enforced via DISCLAIMER_BODY constant below.
// FORBIDDEN language anywhere in this file: "ADA compliant", "lawsuit-proof", "certified accessible"

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib'

// ─── Legal compliance constants ───────────────────────────────────────────────
// S4 spec: exact text required. Do NOT alter.
const DISCLAIMER_BODY =
  'This document is not legal advice. It is a technical assessment generated by ' +
  'automated tooling. Consult a qualified attorney for legal guidance. This scan ' +
  'uses axe-core, which identifies approximately 57% of WCAG 2.1 accessibility ' +
  'issues per Deque Systems research. Manual testing is required for full ' +
  'compliance assessment.'

const FOOTER_NOTICE = 'Not legal advice  |  axe-core ~57% WCAG coverage  |  Consult a qualified attorney'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ViolationSummary {
  id: string
  description: string
  impact: 'critical' | 'serious' | 'moderate' | 'minor' | null
  nodes_affected: number
  wcag_criteria: string[]
}

export interface EvidenceData {
  url: string
  scanDate: Date
  score: number
  tier: 'basic' | 'premium' | 'monitoring'
  violations: ViolationSummary[]
  passCount: number
  incompleteCount: number
}

export interface MonitoringData {
  url: string
  activationDate: Date
  email: string
}

// ─── Remediation hints (dev guide) ───────────────────────────────────────────

interface Hint {
  bad: string
  good: string
  difficulty: 'Low' | 'Medium' | 'High'
  guidance: string
}

const HINTS: Record<string, Hint> = {
  'color-contrast': {
    bad:  '<p style="color: #aaaaaa">Text content</p>',
    good: '<p style="color: #595959">Text content</p>',
    difficulty: 'Medium',
    guidance:
      'Ensure text has at least 4.5:1 contrast ratio against its background ' +
      '(3:1 for large text >= 18pt or 14pt bold). Use a contrast checker to verify your colors.',
  },
  'image-alt': {
    bad:  '<img src="banner.jpg">',
    good: '<img src="banner.jpg" alt="Describe the image content">',
    difficulty: 'Low',
    guidance:
      'Add a descriptive alt attribute to every <img> element. ' +
      'For purely decorative images use alt="" to signal screen readers should skip it.',
  },
  'label': {
    bad:  '<input type="text" name="email">',
    good: '<label for="email">Email address</label>\n<input type="text" id="email" name="email">',
    difficulty: 'Low',
    guidance:
      'Associate every form control with a visible label using matching for/id attributes. ' +
      'Alternatively use aria-label or aria-labelledby on the input.',
  },
  'heading-order': {
    bad:  '<h1>Page Title</h1>  ...  <h3>Section</h3>',
    good: '<h1>Page Title</h1>  ...  <h2>Section</h2>',
    difficulty: 'Low',
    guidance:
      'Heading levels must not skip. Use h1 -> h2 -> h3 in sequence. ' +
      'Never jump from h1 to h3 or h2 to h4.',
  },
  'link-name': {
    bad:  '<a href="/page"><img src="arrow.png"></a>',
    good: '<a href="/page"><img src="arrow.png" alt="View next page"></a>',
    difficulty: 'Low',
    guidance:
      'Every link must have discernible text: visible text content, ' +
      'aria-label, or descriptive alt text on a child image.',
  },
  'button-name': {
    bad:  '<button><img src="close.svg"></button>',
    good: '<button aria-label="Close dialog"><img src="close.svg" alt=""></button>',
    difficulty: 'Low',
    guidance:
      'Every button must have an accessible name via text content, aria-label, or aria-labelledby. ' +
      'Icon-only buttons always need aria-label.',
  },
  'html-has-lang': {
    bad:  '<html>',
    good: '<html lang="en">',
    difficulty: 'Low',
    guidance:
      'Add a lang attribute to the root <html> element using a valid BCP 47 ' +
      'language tag (en, fr, es, etc.).',
  },
  'document-title': {
    bad:  '<title></title>',
    good: '<title>Contact Us - My Business</title>',
    difficulty: 'Low',
    guidance:
      'Every page must have a non-empty, descriptive <title> element. ' +
      'Include both the page name and site name.',
  },
  'aria-required-attr': {
    bad:  '<div role="checkbox">Accept terms</div>',
    good: '<div role="checkbox" aria-checked="false" tabindex="0">Accept terms</div>',
    difficulty: 'Medium',
    guidance:
      'ARIA roles have required properties. The checkbox role requires aria-checked. ' +
      'Check the WAI-ARIA specification for each role\'s required attributes.',
  },
  'frame-title': {
    bad:  '<iframe src="map.html"></iframe>',
    good: '<iframe src="map.html" title="Store location map"></iframe>',
    difficulty: 'Low',
    guidance:
      'Add a descriptive title attribute to all <iframe> elements so screen reader ' +
      'users understand the frame\'s purpose.',
  },
}

const FALLBACK_HINT: Hint = {
  bad:  '<!-- Identify the failing element using browser DevTools -->\n<!-- Inspect for missing ARIA attributes or semantic HTML issues -->',
  good: '<!-- Apply the WCAG-compliant fix per the WAI-ARIA specification -->\n<!-- Test with a screen reader after making changes -->',
  difficulty: 'Medium',
  guidance:
    'Review the WAI-ARIA specification and WCAG 2.1 documentation for this criterion. ' +
    'Use browser accessibility DevTools to identify the affected elements and apply the recommended fix.',
}

// ─── Layout ───────────────────────────────────────────────────────────────────

const W        = 595.28   // A4 width in points
const H        = 841.89   // A4 height in points
const ML       = 50       // margin left
const MR       = 50       // margin right
const TW       = W - ML - MR   // text width = 495.28
const MB       = 50       // margin bottom
const HEADER_H = 68       // blue header bar height

// ─── Colors ───────────────────────────────────────────────────────────────────

const C = {
  primary:  rgb(0.18, 0.32, 0.58),
  dark:     rgb(0.10, 0.10, 0.10),
  muted:    rgb(0.45, 0.45, 0.45),
  light:    rgb(0.82, 0.82, 0.82),
  bg:       rgb(0.95, 0.96, 0.98),
  white:    rgb(1.00, 1.00, 1.00),
  critical: rgb(0.80, 0.10, 0.10),
  serious:  rgb(0.85, 0.42, 0.08),
  moderate: rgb(0.72, 0.58, 0.04),
  minor:    rgb(0.18, 0.44, 0.72),
  green:    rgb(0.10, 0.52, 0.22),
  purple:   rgb(0.42, 0.22, 0.68),
  bgRed:    rgb(0.99, 0.94, 0.94),
  bgGreen:  rgb(0.93, 0.98, 0.94),
  bgAmber:  rgb(1.00, 0.97, 0.93),
}

type PdfColor = ReturnType<typeof rgb>

// ─── Utilities ────────────────────────────────────────────────────────────────

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function scoreColor(score: number): PdfColor {
  if (score >= 90) return C.green
  if (score >= 70) return rgb(0.80, 0.55, 0.05)
  if (score >= 40) return C.serious
  return C.critical
}

function impactColor(impact: ViolationSummary['impact']): PdfColor {
  switch (impact) {
    case 'critical': return C.critical
    case 'serious':  return C.serious
    case 'moderate': return C.moderate
    case 'minor':    return C.minor
    default:         return C.muted
  }
}

// Splits text into wrapped lines that fit maxWidth. Handles long single words by
// leaving them as-is rather than infinite-looping.
function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = []
  let current = ''
  for (const word of text.split(' ')) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines.length > 0 ? lines : ['']
}

interface Fonts { regular: PDFFont; bold: PDFFont; mono: PDFFont }

async function loadFonts(doc: PDFDocument): Promise<Fonts> {
  const [regular, bold, mono] = await Promise.all([
    doc.embedFont(StandardFonts.Helvetica),
    doc.embedFont(StandardFonts.HelveticaBold),
    doc.embedFont(StandardFonts.Courier),
  ])
  return { regular, bold, mono }
}

// Draws wrapped text and returns the y position below the last line
function drawWrapped(
  page: PDFPage,
  text: string,
  x: number,
  startY: number,
  font: PDFFont,
  size: number,
  color: PdfColor,
  maxWidth = TW,
  lineGap = 4,
): number {
  let y = startY
  for (const line of wrapText(text, font, size, maxWidth)) {
    page.drawText(line, { x, y, size, font, color })
    y -= size + lineGap
  }
  return y
}

function drawHRule(page: PDFPage, y: number, color: PdfColor = C.light): void {
  page.drawLine({ start: { x: ML, y }, end: { x: W - MR, y }, thickness: 0.5, color })
}

function drawFooter(page: PDFPage, fonts: Fonts, date: Date): void {
  const y = 30
  drawHRule(page, y + 12)
  page.drawText(`Generated ${fmtDate(date)}  |  ${FOOTER_NOTICE}`, {
    x: ML, y, size: 7, font: fonts.regular, color: C.muted,
  })
}

function drawPageHeader(
  page: PDFPage,
  fonts: Fonts,
  title: string,
  subtitle: string,
  barColor: PdfColor = C.primary,
): void {
  page.drawRectangle({ x: 0, y: H - HEADER_H, width: W, height: HEADER_H, color: barColor })
  page.drawText(title, { x: ML, y: H - 40, size: 18, font: fonts.bold, color: C.white })
  if (subtitle) {
    page.drawText(
      subtitle.length > 70 ? `${subtitle.slice(0, 67)}...` : subtitle,
      { x: ML, y: H - 59, size: 10, font: fonts.regular, color: rgb(0.78, 0.84, 0.96) },
    )
  }
}

// ─── Page builders ────────────────────────────────────────────────────────────

function buildCoverPage(doc: PDFDocument, fonts: Fonts, data: EvidenceData): void {
  const page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'WCAG Technical Evidence Package', 'Accessibility Assessment Report')

  let y = H - HEADER_H - 28

  // Website URL
  page.drawText('Scanned Website', { x: ML, y, size: 9, font: fonts.bold, color: C.muted })
  y -= 17
  const displayUrl = data.url.length > 68 ? `${data.url.slice(0, 65)}...` : data.url
  page.drawText(displayUrl, { x: ML, y, size: 13, font: fonts.bold, color: C.primary })

  // Scan date
  y -= 28
  page.drawText('Scan Date', { x: ML, y, size: 9, font: fonts.bold, color: C.muted })
  y -= 16
  page.drawText(fmtDate(data.scanDate), { x: ML, y, size: 12, font: fonts.regular, color: C.dark })

  // Score block
  y -= 32
  const boxTop = y + 12
  const boxH   = 72
  page.drawRectangle({ x: ML, y: boxTop - boxH, width: TW, height: boxH, color: C.bg })
  page.drawText('Accessibility Score', { x: ML + 12, y: boxTop - 16, size: 10, font: fonts.bold, color: C.muted })
  const scoreStr = String(data.score)
  page.drawText(scoreStr, { x: ML + 12, y: boxTop - 55, size: 38, font: fonts.bold, color: scoreColor(data.score) })
  page.drawText('/ 100', {
    x: ML + 16 + fonts.bold.widthOfTextAtSize(scoreStr, 38),
    y: boxTop - 44, size: 14, font: fonts.regular, color: C.muted,
  })
  const scoreLabel =
    data.score >= 90 ? 'Good — minor improvements recommended' :
    data.score >= 70 ? 'Fair — several issues require attention' :
    data.score >= 40 ? 'Poor — significant accessibility barriers found' :
                       'Critical — major accessibility barriers present'
  page.drawText(scoreLabel, {
    x: ML + 145, y: boxTop - 38, size: 10, font: fonts.regular, color: scoreColor(data.score),
  })

  y = boxTop - boxH - 18

  // Violation counts row
  const impacts = [
    { label: 'Critical', color: C.critical, count: data.violations.filter(v => v.impact === 'critical').length },
    { label: 'Serious',  color: C.serious,  count: data.violations.filter(v => v.impact === 'serious').length },
    { label: 'Moderate', color: C.moderate, count: data.violations.filter(v => v.impact === 'moderate').length },
    { label: 'Minor',    color: C.minor,    count: data.violations.filter(v => v.impact === 'minor').length },
  ]
  let bx = ML
  for (const item of impacts) {
    page.drawRectangle({ x: bx, y: y - 36, width: 112, height: 46, color: C.bg })
    page.drawText(String(item.count), { x: bx + 10, y: y - 4, size: 22, font: fonts.bold, color: item.color })
    page.drawText(item.label, { x: bx + 10, y: y - 24, size: 9, font: fonts.regular, color: C.muted })
    bx += 122
  }

  // Tier badge
  y -= 58
  const tierText: Record<string, string> = {
    basic:      'Basic  -  Evidence Package',
    premium:    'Premium  -  Evidence Package + Developer Guide',
    monitoring: 'Monitoring  -  Evidence Package + Monthly Scans',
  }
  const tierColor: Record<string, PdfColor> = {
    basic: C.primary, premium: C.purple, monitoring: C.green,
  }
  const tLabel = tierText[data.tier] ?? data.tier
  const tColor = tierColor[data.tier] ?? C.primary
  const badgeW = fonts.bold.widthOfTextAtSize(tLabel, 10) + 22
  page.drawRectangle({ x: ML, y: y - 8, width: badgeW, height: 22, color: tColor })
  page.drawText(tLabel, { x: ML + 11, y: y - 1, size: 10, font: fonts.bold, color: C.white })

  // Coverage note
  y -= 36
  drawWrapped(
    page,
    'Note: Automated scanning detects approximately 57% of WCAG 2.1 issues. ' +
    'Manual testing is required for a complete accessibility assessment.',
    ML, y, fonts.regular, 8, C.muted, TW, 3,
  )

  drawFooter(page, fonts, data.scanDate)
}

function buildDisclaimerPage(doc: PDFDocument, fonts: Fonts, date: Date): void {
  const page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'Important Legal Notice', 'Please read before using this document')

  let y = H - HEADER_H - 28

  // Amber disclaimer box with left accent bar
  const disclaimerBoxH = 145
  page.drawRectangle({ x: ML, y: y - disclaimerBoxH, width: TW, height: disclaimerBoxH, color: C.bgAmber })
  page.drawRectangle({ x: ML, y: y - disclaimerBoxH, width: 4, height: disclaimerBoxH, color: C.serious })
  y -= 16
  page.drawText('Legal Disclaimer', { x: ML + 14, y, size: 13, font: fonts.bold, color: C.dark })
  y -= 18
  y = drawWrapped(page, DISCLAIMER_BODY, ML + 14, y, fonts.regular, 10.5, C.dark, TW - 24, 4)

  y -= 26
  page.drawText('Coverage Disclosure', { x: ML, y, size: 13, font: fonts.bold, color: C.dark })
  y -= 18
  y = drawWrapped(
    page,
    'axe-core is an industry-standard automated accessibility testing tool developed by Deque Systems. ' +
    'Based on Deque\'s analysis of over 2,000 audits and 300,000 accessibility issues, automated tools ' +
    'identify approximately 57% of WCAG 2.1 Level AA issues. The remaining issues require manual review ' +
    'by a qualified accessibility specialist.',
    ML, y, fonts.regular, 10.5, C.dark, TW, 4,
  )

  y -= 26
  page.drawText('Intended Use of This Document', { x: ML, y, size: 13, font: fonts.bold, color: C.dark })
  y -= 18
  drawWrapped(
    page,
    'This report documents accessibility testing performed in good faith as part of a remediation effort. ' +
    'It demonstrates technical diligence and is intended to support an attorney\'s review of ' +
    'accessibility-related matters. It is not a certification, guarantee, or legal opinion.',
    ML, y, fonts.regular, 10.5, C.dark, TW, 4,
  )

  drawFooter(page, fonts, date)
}

function buildSummaryPage(doc: PDFDocument, fonts: Fonts, data: EvidenceData): void {
  const page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'Executive Summary', data.url)

  let y = H - HEADER_H - 28

  // Score row
  page.drawText('Overall Score', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  const scoreLine = `${data.score} / 100`
  page.drawText(scoreLine, {
    x: W - MR - fonts.bold.widthOfTextAtSize(scoreLine, 13),
    y, size: 13, font: fonts.bold, color: scoreColor(data.score),
  })
  y -= 18
  drawHRule(page, y)
  y -= 18

  const rows: Array<[string, number, PdfColor?]> = [
    ['Total violations found',   data.violations.length],
    ['Critical violations',      data.violations.filter(v => v.impact === 'critical').length, C.critical],
    ['Serious violations',       data.violations.filter(v => v.impact === 'serious').length,  C.serious],
    ['Moderate violations',      data.violations.filter(v => v.impact === 'moderate').length, C.moderate],
    ['Minor violations',         data.violations.filter(v => v.impact === 'minor').length,    C.minor],
    ['Checks passed',            data.passCount, C.green],
    ['Requires manual review',   data.incompleteCount],
  ]

  for (const [label, value, color] of rows) {
    page.drawText(label, { x: ML, y, size: 11, font: fonts.regular, color: C.dark })
    page.drawText(String(value), { x: ML + 220, y, size: 11, font: fonts.bold, color: color ?? C.dark })
    y -= 20
  }

  y -= 10
  drawHRule(page, y)
  y -= 20

  page.drawText('Scan Scope', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  y -= 16
  y = drawWrapped(
    page,
    'This scan tested against WCAG 2.1 Level A and Level AA success criteria using axe-core rules: ' +
    'wcag2a, wcag2aa, wcag21aa. Automated testing identifies approximately 57% of applicable issues ' +
    '— manual review is required for complete coverage.',
    ML, y, fonts.regular, 10, C.muted, TW, 4,
  )

  y -= 20
  page.drawText('Remediation Priority', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  y -= 16
  drawWrapped(
    page,
    'Address Critical violations first — they prevent some users from accessing content entirely. ' +
    'Then address Serious, Moderate, and Minor violations in order. Each violation in this report ' +
    'includes the WCAG criterion to help guide the remediation.',
    ML, y, fonts.regular, 10, C.muted, TW, 4,
  )

  drawFooter(page, fonts, data.scanDate)
}

function buildViolationPages(doc: PDFDocument, fonts: Fonts, data: EvidenceData): void {
  const shown   = data.violations.slice(0, 20)
  const hasMore = data.violations.length > 20

  let page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'Violations Detail', `${shown.length} of ${data.violations.length} violations`)
  let y = H - HEADER_H - 22
  let firstOnPage = true

  for (let i = 0; i < shown.length; i++) {
    const v      = shown[i]!
    const impact = v.impact ?? 'unknown'
    const color  = impactColor(v.impact)
    const descLines = wrapText(v.description, fonts.regular, 10, TW - 12)
    // Conservative height estimate: badge row + description + wcag + nodes + gap
    const neededH = 18 + descLines.length * 14 + (v.wcag_criteria.length > 0 ? 14 : 0) + 14 + 24

    if (!firstOnPage && y - neededH < MB + 40) {
      drawFooter(page, fonts, data.scanDate)
      page = doc.addPage([W, H])
      drawPageHeader(page, fonts, 'Violations Detail (continued)', '')
      y = H - HEADER_H - 22
    }
    firstOnPage = false

    // Impact badge + violation ID
    const badgeLabel = impact.toUpperCase()
    const badgeW     = fonts.bold.widthOfTextAtSize(badgeLabel, 8) + 14
    page.drawRectangle({ x: ML, y: y - 5, width: badgeW, height: 16, color })
    page.drawText(badgeLabel, { x: ML + 7, y: y - 1, size: 8, font: fonts.bold, color: C.white })
    page.drawText(v.id, { x: ML + badgeW + 8, y, size: 9.5, font: fonts.mono, color: C.dark })
    y -= 18

    // Description
    for (const line of descLines) {
      page.drawText(line, { x: ML + 10, y, size: 10, font: fonts.regular, color: C.dark })
      y -= 14
    }

    // WCAG criteria
    if (v.wcag_criteria.length > 0) {
      page.drawText(`WCAG: ${v.wcag_criteria.join(', ')}`, {
        x: ML + 10, y, size: 9, font: fonts.regular, color: C.muted,
      })
      y -= 14
    }

    // Elements affected
    page.drawText(
      `${v.nodes_affected} element${v.nodes_affected !== 1 ? 's' : ''} affected`,
      { x: ML + 10, y, size: 9, font: fonts.regular, color: C.muted },
    )
    y -= 22

    // Separator (skip after last)
    if (i < shown.length - 1) {
      page.drawLine({ start: { x: ML, y: y + 10 }, end: { x: W - MR, y: y + 10 }, thickness: 0.3, color: C.light })
    }
  }

  if (hasMore) {
    y -= 6
    page.drawText(
      `+ ${data.violations.length - 20} additional violations not shown. Remediate the above issues first.`,
      { x: ML, y, size: 9, font: fonts.regular, color: C.muted },
    )
  }

  drawFooter(page, fonts, data.scanDate)
}

function buildDevGuidePages(doc: PDFDocument, fonts: Fonts, data: EvidenceData): void {
  // Guide cover
  const cover = doc.addPage([W, H])
  drawPageHeader(cover, fonts, 'Developer Remediation Guide', data.url, C.purple)

  let y = H - HEADER_H - 28
  cover.drawText('About This Guide', { x: ML, y, size: 13, font: fonts.bold, color: C.dark })
  y -= 18
  drawWrapped(
    cover,
    'This guide lists the top WCAG accessibility violations found on your site and provides ' +
    'concrete code examples showing the issue (Before) and the fix (After). Examples are ' +
    'representative patterns — adapt them to match your specific implementation.',
    ML, y, fonts.regular, 11, C.dark, TW, 5,
  )
  drawFooter(cover, fonts, data.scanDate)

  // Mandatory disclaimer page in every PDF
  buildDisclaimerPage(doc, fonts, data.scanDate)

  // Sort by impact severity, take top 10
  const order = ['critical', 'serious', 'moderate', 'minor']
  const top10 = [...data.violations]
    .sort((a, b) => order.indexOf(a.impact ?? 'minor') - order.indexOf(b.impact ?? 'minor'))
    .slice(0, 10)

  let page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'Remediation Instructions', `${top10.length} highest-impact issues`, C.purple)
  y = H - HEADER_H - 22
  let firstOnPage = true

  for (let i = 0; i < top10.length; i++) {
    const v = top10[i]!
    const hint = HINTS[v.id] ?? FALLBACK_HINT
    const badLines      = hint.bad.split('\n')
    const goodLines     = hint.good.split('\n')
    const guidanceLines = wrapText(hint.guidance, fonts.regular, 10, TW - 12)

    const neededH =
      18 +                                // badge + id
      14 +                                // wcag line (approximate)
      14 +                                // difficulty line
      guidanceLines.length * 14 +         // guidance
      14 + badLines.length * 12 + 14 +    // bad block
      14 + goodLines.length * 12 + 24     // good block + gap

    if (!firstOnPage && y - neededH < MB + 40) {
      drawFooter(page, fonts, data.scanDate)
      page = doc.addPage([W, H])
      drawPageHeader(page, fonts, 'Remediation Instructions (continued)', '', C.purple)
      y = H - HEADER_H - 22
    }
    firstOnPage = false

    const impact     = v.impact ?? 'unknown'
    const color      = impactColor(v.impact)
    const badgeLabel = impact.toUpperCase()
    const badgeW     = fonts.bold.widthOfTextAtSize(badgeLabel, 8) + 14

    // Badge + id row
    page.drawRectangle({ x: ML, y: y - 5, width: badgeW, height: 16, color })
    page.drawText(badgeLabel, { x: ML + 7, y: y - 1, size: 8, font: fonts.bold, color: C.white })
    page.drawText(v.id, { x: ML + badgeW + 8, y, size: 9.5, font: fonts.mono, color: C.dark })
    y -= 18

    // Description
    y = drawWrapped(page, v.description, ML + 10, y, fonts.regular, 10, C.dark, TW - 10, 3)

    // WCAG criteria
    if (v.wcag_criteria.length > 0) {
      page.drawText(`WCAG: ${v.wcag_criteria.join(', ')}`, {
        x: ML + 10, y, size: 9, font: fonts.regular, color: C.muted,
      })
      y -= 14
    }

    // Fix effort
    const diffColor = hint.difficulty === 'Low' ? C.green : hint.difficulty === 'High' ? C.critical : C.serious
    page.drawText(`Fix effort: ${hint.difficulty}`, { x: ML + 10, y, size: 9, font: fonts.bold, color: diffColor })
    y -= 14

    // Guidance text
    y = drawWrapped(page, hint.guidance, ML + 10, y, fonts.regular, 9.5, C.muted, TW - 10, 3)
    y -= 6

    // Before (bad) code block
    page.drawText('Before (issue present):', { x: ML + 10, y, size: 8.5, font: fonts.bold, color: C.critical })
    y -= 12
    const badBoxH = badLines.length * 12 + 8
    page.drawRectangle({ x: ML + 10, y: y - badBoxH, width: TW - 20, height: badBoxH, color: C.bgRed })
    y -= 5
    for (const line of badLines) {
      page.drawText(line, { x: ML + 16, y, size: 8, font: fonts.mono, color: C.dark })
      y -= 12
    }
    y -= 5

    // After (good) code block
    page.drawText('After (accessible):', { x: ML + 10, y, size: 8.5, font: fonts.bold, color: C.green })
    y -= 12
    const goodBoxH = goodLines.length * 12 + 8
    page.drawRectangle({ x: ML + 10, y: y - goodBoxH, width: TW - 20, height: goodBoxH, color: C.bgGreen })
    y -= 5
    for (const line of goodLines) {
      page.drawText(line, { x: ML + 16, y, size: 8, font: fonts.mono, color: C.dark })
      y -= 12
    }
    y -= 20

    if (i < top10.length - 1) {
      page.drawLine({ start: { x: ML, y: y + 10 }, end: { x: W - MR, y: y + 10 }, thickness: 0.3, color: C.light })
    }
  }

  drawFooter(page, fonts, data.scanDate)
}

function buildMonitoringPage(doc: PDFDocument, fonts: Fonts, data: MonitoringData): void {
  const page = doc.addPage([W, H])
  drawPageHeader(page, fonts, 'Monitoring Activated', 'WCAG Accessibility Monitoring', C.green)

  let y = H - HEADER_H - 28

  // Status banner
  page.drawRectangle({ x: ML, y: y - 50, width: TW, height: 62, color: C.bgGreen })
  page.drawText('Active', { x: ML + 14, y: y - 10, size: 24, font: fonts.bold, color: C.green })
  page.drawText('Monthly accessibility scans are now scheduled for your website.', {
    x: ML + 14, y: y - 33, size: 10, font: fonts.regular, color: C.dark,
  })

  y -= 72

  const details: Array<[string, string]> = [
    ['Website',         data.url.length > 55 ? `${data.url.slice(0, 52)}...` : data.url],
    ['Activation Date', fmtDate(data.activationDate)],
    ['Alert Email',     data.email],
    ['Scan Schedule',   '1st of each month'],
    ['Alert Threshold', 'Email alert when score drops below 70'],
    ['Standard',        'WCAG 2.1 Level AA (wcag2a, wcag2aa, wcag21aa)'],
  ]

  for (const [label, value] of details) {
    page.drawText(label, { x: ML, y, size: 10, font: fonts.bold, color: C.muted })
    page.drawText(value, { x: ML + 148, y, size: 10, font: fonts.regular, color: C.dark })
    y -= 22
  }

  y -= 14
  drawHRule(page, y)
  y -= 20

  page.drawText('Important Legal Notice', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  y -= 16
  drawWrapped(page, DISCLAIMER_BODY, ML, y, fonts.regular, 9, C.muted, TW, 4)

  drawFooter(page, fonts, data.activationDate)
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateEvidencePackage(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildCoverPage(doc, fonts, data)
  buildDisclaimerPage(doc, fonts, data.scanDate)
  buildSummaryPage(doc, fonts, data)
  buildViolationPages(doc, fonts, data)
  return doc.save()
}

export async function generateDevGuide(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildDevGuidePages(doc, fonts, data)
  return doc.save()
}

export async function generateMonitoringConfirmation(data: MonitoringData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildMonitoringPage(doc, fonts, data)
  return doc.save()
}
