// Every PDF generated here MUST carry the legal disclaimer and ~57% axe-core coverage
// disclosure. CLAUDE.md Hard Rule 5 & 6 — enforced via DISCLAIMER_BODY constant below.
// FORBIDDEN language anywhere in this file: "ADA compliant", "lawsuit-proof", "certified accessible"

import {
  PDFDocument,
  StandardFonts,
  rgb,
  LineCapStyle,
  type PDFFont,
  type PDFPage,
} from 'pdf-lib'

// ─── Legal compliance constants ───────────────────────────────────────────────

const DISCLAIMER_BODY =
  'This report is a technical evidence package and does not constitute legal advice. ' +
  'Consult a qualified attorney for legal guidance. This assessment was generated by ' +
  'automated tooling using axe-core, which identifies approximately 57% of WCAG 2.2 ' +
  'accessibility issues per Deque Systems research. Manual testing is required for ' +
  'full compliance assessment.'

const FOOTER_NOTICE = 'Not legal advice  |  axe-core ~57% WCAG 2.2 coverage'

const COVER_DISCLAIMER =
  'IMPORTANT: This document is a technical assessment generated by automated tooling. ' +
  'It is NOT legal advice and does not constitute a compliance certification. This scan ' +
  'uses axe-core, which identifies approximately 57% of WCAG 2.2 accessibility issues. ' +
  'Always consult a qualified attorney.'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ViolationSummary {
  id: string
  description: string
  impact: 'critical' | 'serious' | 'moderate' | 'minor' | null
  nodes_affected: number
  wcag_criteria: string[]
}

export interface EnhancedViolation {
  originalId:     string
  plainEnglish:   string
  businessImpact: string
  fixDifficulty:  'Easy' | 'Medium' | 'Hard'
  estimatedTime:  string
}

export interface EvidenceData {
  url: string
  businessName?: string | null
  scanDate: Date
  score: number
  tier: 'basic' | 'premium' | 'monitoring'
  violations: ViolationSummary[]
  enhancedViolations?: EnhancedViolation[]
  passCount: number
  incompleteCount: number
}

export interface MonitoringData {
  url: string
  activationDate: Date
  email: string
}

// ─── Remediation hints (dev guide) ───────────────────────────────────────────

interface Hint {
  bad: string
  good: string
  difficulty: 'Low' | 'Medium' | 'High'
  guidance: string
}

const HINTS: Record<string, Hint> = {
  'color-contrast': {
    bad:  '<p style="color: #aaaaaa">Text content</p>',
    good: '<p style="color: #595959">Text content</p>',
    difficulty: 'Medium',
    guidance:
      'Ensure text has at least 4.5:1 contrast ratio against its background ' +
      '(3:1 for large text >= 18pt or 14pt bold). Use a contrast checker to verify your colors.',
  },
  'image-alt': {
    bad:  '<img src="banner.jpg">',
    good: '<img src="banner.jpg" alt="Describe the image content">',
    difficulty: 'Low',
    guidance:
      'Add a descriptive alt attribute to every <img> element. ' +
      'For purely decorative images use alt="" to signal screen readers should skip it.',
  },
  'label': {
    bad:  '<input type="text" name="email">',
    good: '<label for="email">Email address</label>\n<input type="text" id="email" name="email">',
    difficulty: 'Low',
    guidance:
      'Associate every form control with a visible label using matching for/id attributes. ' +
      'Alternatively use aria-label or aria-labelledby on the input.',
  },
  'heading-order': {
    bad:  '<h1>Page Title</h1>  ...  <h3>Section</h3>',
    good: '<h1>Page Title</h1>  ...  <h2>Section</h2>',
    difficulty: 'Low',
    guidance:
      'Heading levels must not skip. Use h1 -> h2 -> h3 in sequence. ' +
      'Never jump from h1 to h3 or h2 to h4.',
  },
  'link-name': {
    bad:  '<a href="/page"><img src="arrow.png"></a>',
    good: '<a href="/page"><img src="arrow.png" alt="View next page"></a>',
    difficulty: 'Low',
    guidance:
      'Every link must have discernible text: visible text content, ' +
      'aria-label, or descriptive alt text on a child image.',
  },
  'button-name': {
    bad:  '<button><img src="close.svg"></button>',
    good: '<button aria-label="Close dialog"><img src="close.svg" alt=""></button>',
    difficulty: 'Low',
    guidance:
      'Every button must have an accessible name via text content, aria-label, or aria-labelledby. ' +
      'Icon-only buttons always need aria-label.',
  },
  'html-has-lang': {
    bad:  '<html>',
    good: '<html lang="en">',
    difficulty: 'Low',
    guidance:
      'Add a lang attribute to the root <html> element using a valid BCP 47 ' +
      'language tag (en, fr, es, etc.).',
  },
  'document-title': {
    bad:  '<title></title>',
    good: '<title>Contact Us - My Business</title>',
    difficulty: 'Low',
    guidance:
      'Every page must have a non-empty, descriptive <title> element. ' +
      'Include both the page name and site name.',
  },
  'aria-required-attr': {
    bad:  '<div role="checkbox">Accept terms</div>',
    good: '<div role="checkbox" aria-checked="false" tabindex="0">Accept terms</div>',
    difficulty: 'Medium',
    guidance:
      'ARIA roles have required properties. The checkbox role requires aria-checked. ' +
      'Check the WAI-ARIA specification for each role\'s required attributes.',
  },
  'frame-title': {
    bad:  '<iframe src="map.html"></iframe>',
    good: '<iframe src="map.html" title="Store location map"></iframe>',
    difficulty: 'Low',
    guidance:
      'Add a descriptive title attribute to all <iframe> elements so screen reader ' +
      'users understand the frame\'s purpose.',
  },
}

const FALLBACK_HINT: Hint = {
  bad:  '<!-- Identify the failing element using browser DevTools -->\n<!-- Inspect for missing ARIA attributes or semantic HTML issues -->',
  good: '<!-- Apply the WCAG-compliant fix per the WAI-ARIA specification -->\n<!-- Test with a screen reader after making changes -->',
  difficulty: 'Medium',
  guidance:
    'Review the WAI-ARIA specification and WCAG 2.2 documentation for this criterion. ' +
    'Use browser accessibility DevTools to identify the affected elements and apply the recommended fix.',
}

// ─── Layout constants ─────────────────────────────────────────────────────────

const W  = 595.28              // A4 width
const H  = 841.89              // A4 height
const M  = 48                  // margin all sides
const CW = W - M * 2           // content width (499.28)
const HEAD_H = 36              // inner-page header strip
const CONTENT_TOP = H - HEAD_H - 28
const CONTENT_BOTTOM = 48

// ─── Colors ───────────────────────────────────────────────────────────────────

type PdfColor = ReturnType<typeof rgb>

const C = {
  navy:     rgb(0.102, 0.153, 0.361),  // #1a274c
  accent:   rgb(0.231, 0.510, 0.965),  // #3b82f6
  textDark: rgb(0.059, 0.090, 0.165),  // #0f172a
  textMid:  rgb(0.278, 0.333, 0.412),  // #475569
  muted:    rgb(0.392, 0.455, 0.545),  // #64748b
  faint:    rgb(0.580, 0.639, 0.722),  // #94a3b8
  border:   rgb(0.886, 0.910, 0.941),  // #e2e8f0
  bgPage:   rgb(0.973, 0.980, 0.988),  // #f8fafc
  white:    rgb(1, 1, 1),

  danger:   rgb(0.863, 0.149, 0.149),  // #dc2626
  warning:  rgb(0.851, 0.467, 0.024),  // #d97706
  success:  rgb(0.086, 0.639, 0.290),  // #16a34a

  critical: rgb(0.863, 0.149, 0.149),  // #dc2626
  serious:  rgb(0.976, 0.451, 0.086),  // #f97316
  moderate: rgb(0.851, 0.467, 0.024),  // #d97706
  minor:    rgb(0.231, 0.510, 0.965),  // #3b82f6

  amberBg:  rgb(1.000, 0.984, 0.922),  // #fffbeb
  amberFg:  rgb(0.573, 0.251, 0.055),  // #92400e
  amberTxt: rgb(0.471, 0.208, 0.059),  // #78350f
  blueBg:   rgb(0.937, 0.965, 1.000),  // #eff6ff
  blueFg:   rgb(0.118, 0.251, 0.686),  // #1e40af
  blueTxt:  rgb(0.118, 0.227, 0.541),  // #1e3a8a
}

// 12% tint of a color over white — used for "severity-dim" fills
function dim(c: PdfColor): PdfColor {
  return rgb(1 - 0.12 * (1 - c.red), 1 - 0.12 * (1 - c.green), 1 - 0.12 * (1 - c.blue))
}

function impactColor(impact: ViolationSummary['impact']): PdfColor {
  switch (impact) {
    case 'critical': return C.critical
    case 'serious':  return C.serious
    case 'moderate': return C.moderate
    default:         return C.minor
  }
}

function scoreColor(score: number): PdfColor {
  if (score >= 80) return C.success
  if (score >= 60) return C.warning
  return C.danger
}

function scoreLabel(score: number): string {
  if (score >= 80) return 'GOOD STANDING'
  if (score >= 60) return 'NEEDS REMEDIATION'
  return 'CRITICAL RISK'
}

// ─── Utilities ────────────────────────────────────────────────────────────────

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = []
  let current = ''
  for (const word of text.split(' ')) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines.length > 0 ? lines : ['']
}

function truncate(text: string, font: PDFFont, size: number, maxWidth: number): string {
  if (font.widthOfTextAtSize(text, size) <= maxWidth) return text
  let t = text
  while (t.length > 1 && font.widthOfTextAtSize(`${t}...`, size) > maxWidth) {
    t = t.slice(0, -1)
  }
  return `${t}...`
}

interface Fonts { regular: PDFFont; bold: PDFFont; italic: PDFFont; mono: PDFFont }

async function loadFonts(doc: PDFDocument): Promise<Fonts> {
  const [regular, bold, italic, mono] = await Promise.all([
    doc.embedFont(StandardFonts.Helvetica),
    doc.embedFont(StandardFonts.HelveticaBold),
    doc.embedFont(StandardFonts.HelveticaOblique),
    doc.embedFont(StandardFonts.Courier),
  ])
  return { regular, bold, italic, mono }
}

// Rounded rectangle via SVG path. yTop is the PDF y of the TOP edge.
function svgRoundedRect(w: number, h: number, r: number): string {
  return (
    `M ${r},0 H ${w - r} A ${r},${r} 0 0 1 ${w},${r} V ${h - r} ` +
    `A ${r},${r} 0 0 1 ${w - r},${h} H ${r} A ${r},${r} 0 0 1 0,${h - r} V ${r} ` +
    `A ${r},${r} 0 0 1 ${r},0 Z`
  )
}

// Rounded only at the top corners (card header strips)
function svgRoundedRectTop(w: number, h: number, r: number): string {
  return (
    `M ${r},0 H ${w - r} A ${r},${r} 0 0 1 ${w},${r} V ${h} H 0 V ${r} ` +
    `A ${r},${r} 0 0 1 ${r},0 Z`
  )
}

interface RectOpts {
  color?: PdfColor
  borderColor?: PdfColor
  borderWidth?: number
  opacity?: number
}

function drawRoundedRect(
  page: PDFPage, x: number, yTop: number, w: number, h: number, r: number, opts: RectOpts,
): void {
  page.drawSvgPath(svgRoundedRect(w, h, r), { x, y: yTop, ...opts })
}

function drawPill(
  page: PDFPage, x: number, yTop: number, w: number, h: number, color: PdfColor,
): void {
  drawRoundedRect(page, x, yTop, w, h, h / 2, { color })
}

function drawWrapped(
  page: PDFPage,
  text: string,
  x: number,
  startY: number,
  font: PDFFont,
  size: number,
  color: PdfColor,
  maxWidth = CW,
  lineGap = 5,
): number {
  let y = startY
  for (const line of wrapText(text, font, size, maxWidth)) {
    page.drawText(line, { x, y, size, font, color })
    y -= size + lineGap
  }
  return y
}

// ─── Page chrome (two-pass: drawn after all pages exist for "Page X of Y") ───

function applyChrome(
  pages: PDFPage[],
  fonts: Fonts,
  docTitle: string,
  date: Date,
  skipFirst: boolean,
): void {
  const total = pages.length
  for (let i = skipFirst ? 1 : 0; i < total; i++) {
    const page = pages[i]!

    // Header strip
    page.drawRectangle({ x: 0, y: H - HEAD_H, width: W, height: HEAD_H, color: C.navy })
    page.drawText(docTitle, { x: M, y: H - 23, size: 10, font: fonts.bold, color: C.white })
    const pn = `Page ${i + 1} of ${total}`
    page.drawText(pn, {
      x: W - M - fonts.regular.widthOfTextAtSize(pn, 10),
      y: H - 23,
      size: 10, font: fonts.regular, color: C.white,
    })

    // Footer
    page.drawLine({
      start: { x: M, y: 26 }, end: { x: W - M, y: 26 },
      thickness: 1, color: C.border,
    })
    const footer = `${FOOTER_NOTICE}  |  Generated ${fmtDate(date)}`
    page.drawText(footer, {
      x: (W - fonts.regular.widthOfTextAtSize(footer, 9)) / 2,
      y: 12,
      size: 9, font: fonts.regular, color: C.faint,
    })
  }
}

function addContentPage(doc: PDFDocument, pages: PDFPage[]): PDFPage {
  const page = doc.addPage([W, H])
  page.drawRectangle({ x: 0, y: 0, width: W, height: H, color: C.white })
  pages.push(page)
  return page
}

// Section with title, left accent bar, and body text. Returns new y.
function drawSection(
  page: PDFPage,
  fonts: Fonts,
  title: string,
  body: string,
  y: number,
  accentColor: PdfColor = C.accent,
): number {
  const bodyLines = wrapText(body, fonts.regular, 11, CW - 14)
  const blockH = 20 + bodyLines.length * 18
  page.drawRectangle({ x: M, y: y - blockH + 12, width: 3, height: blockH, color: accentColor })
  page.drawText(title, { x: M + 12, y, size: 12, font: fonts.bold, color: C.navy })
  let by = y - 22
  for (const line of bodyLines) {
    page.drawText(line, { x: M + 12, y: by, size: 11, font: fonts.regular, color: C.textMid })
    by -= 18
  }
  return by - 14
}

// ─── Cover page ───────────────────────────────────────────────────────────────

const TIER_LABEL: Record<string, string> = {
  basic:      'Basic Package',
  premium:    'Premium Package',
  monitoring: 'Monitoring Package',
}

function buildCoverPage(doc: PDFDocument, pages: PDFPage[], fonts: Fonts, data: EvidenceData): void {
  const page = addContentPage(doc, pages)
  page.drawRectangle({ x: 0, y: 0, width: W, height: H, color: C.bgPage })

  // 1. Navy header strip (top 200pt)
  page.drawRectangle({ x: 0, y: H - 200, width: W, height: 200, color: C.navy })

  page.drawText('WCAG ACCESSIBILITY ASSESSMENT', {
    x: M, y: H - 62, size: 10, font: fonts.bold, color: C.white, opacity: 0.6,
  })
  page.drawText('WCAG Technical', { x: M, y: H - 102, size: 28, font: fonts.bold, color: C.white })
  page.drawText('Evidence Package', { x: M, y: H - 136, size: 28, font: fonts.bold, color: C.white })

  const genStr = `Generated ${fmtDate(data.scanDate)}`
  page.drawText(genStr, {
    x: W - M - fonts.regular.widthOfTextAtSize(genStr, 9),
    y: H - 62,
    size: 9, font: fonts.regular, color: C.white, opacity: 0.7,
  })

  // 2. Blue accent bar
  page.drawRectangle({ x: 0, y: H - 208, width: W, height: 8, color: C.accent })

  // 3. Info card (2x2 grid)
  const cardTop = H - 238
  const cardH   = 130
  drawRoundedRect(page, M, cardTop, CW, cardH, 8, {
    color: C.white, borderColor: C.border, borderWidth: 1,
  })

  const col1 = M + 24
  const col2 = M + CW / 2 + 12
  const colW = CW / 2 - 40

  // Row 1
  page.drawText('SCANNED WEBSITE', { x: col1, y: cardTop - 28, size: 8, font: fonts.bold, color: C.muted })
  page.drawText(truncate(data.url, fonts.bold, 12, colW), {
    x: col1, y: cardTop - 44, size: 12, font: fonts.bold, color: C.accent,
  })
  page.drawText('ASSESSMENT DATE', { x: col2, y: cardTop - 28, size: 8, font: fonts.bold, color: C.muted })
  page.drawText(fmtDate(data.scanDate), { x: col2, y: cardTop - 44, size: 11, font: fonts.regular, color: C.textDark })

  // Row 2
  if (data.businessName) {
    page.drawText('BUSINESS NAME', { x: col1, y: cardTop - 78, size: 8, font: fonts.bold, color: C.muted })
    page.drawText(truncate(data.businessName, fonts.bold, 12, colW), {
      x: col1, y: cardTop - 94, size: 12, font: fonts.bold, color: C.textDark,
    })
  } else {
    page.drawText('ASSESSMENT STANDARD', { x: col1, y: cardTop - 78, size: 8, font: fonts.bold, color: C.muted })
    page.drawText('WCAG 2.2 Level AA', { x: col1, y: cardTop - 94, size: 11, font: fonts.regular, color: C.textDark })
  }
  page.drawText('REPORT TYPE', { x: col2, y: cardTop - 78, size: 8, font: fonts.bold, color: C.muted })
  page.drawText(TIER_LABEL[data.tier] ?? data.tier, {
    x: col2, y: cardTop - 94, size: 11, font: fonts.regular, color: C.textDark,
  })

  // 4. Score circle
  const cx = W / 2
  const cy = H - 455
  const r  = 60
  const sc = scoreColor(data.score)

  page.drawEllipse({
    x: cx, y: cy, xScale: r, yScale: r,
    color: sc, opacity: 0.1,
    borderColor: sc, borderWidth: 4, borderOpacity: 1,
  })

  const scoreStr = String(data.score)
  const sw  = fonts.bold.widthOfTextAtSize(scoreStr, 42)
  const sufW = fonts.regular.widthOfTextAtSize('/100', 18)
  const x0 = cx - (sw + 4 + sufW) / 2
  page.drawText(scoreStr, { x: x0, y: cy - 14, size: 42, font: fonts.bold, color: sc })
  page.drawText('/100', { x: x0 + sw + 4, y: cy - 14, size: 18, font: fonts.regular, color: C.faint })

  const label = scoreLabel(data.score)
  page.drawText(label, {
    x: cx - fonts.bold.widthOfTextAtSize(label, 11) / 2,
    y: cy - r - 24,
    size: 11, font: fonts.bold, color: sc,
  })

  // 5. Violation summary boxes
  const counts: Array<{ label: string; color: PdfColor; n: number }> = [
    { label: 'Critical', color: C.critical, n: data.violations.filter(v => v.impact === 'critical').length },
    { label: 'Serious',  color: C.serious,  n: data.violations.filter(v => v.impact === 'serious').length },
    { label: 'Moderate', color: C.moderate, n: data.violations.filter(v => v.impact === 'moderate').length },
    { label: 'Minor',    color: C.minor,    n: data.violations.filter(v => v.impact === 'minor' || v.impact === null).length },
  ]

  const boxTop = H - 580
  const boxXs  = [M, M + 126, M + 252, M + 378]
  counts.forEach((item, i) => {
    const bx = boxXs[i]!
    drawRoundedRect(page, bx, boxTop, 120, 70, 6, {
      color: dim(item.color), borderColor: item.color, borderWidth: 1,
    })
    page.drawText(String(item.n), { x: bx + 14, y: boxTop - 34, size: 24, font: fonts.bold, color: item.color })
    page.drawText(item.label,     { x: bx + 14, y: boxTop - 54, size: 9,  font: fonts.regular, color: C.muted })
  })

  // 6. Footer disclaimer band
  const bandTop = H - 730
  page.drawRectangle({ x: 0, y: bandTop - 80, width: W, height: 80, color: C.amberBg })
  page.drawLine({
    start: { x: 0, y: bandTop }, end: { x: W, y: bandTop },
    thickness: 1, color: C.warning,
  })
  let dy = bandTop - 20
  for (const line of wrapText(COVER_DISCLAIMER, fonts.regular, 10, CW)) {
    page.drawText(line, { x: M, y: dy, size: 10, font: fonts.regular, color: C.amberFg })
    dy -= 14
  }

  const bottom = `${FOOTER_NOTICE}  |  Consult a qualified attorney`
  page.drawText(bottom, {
    x: (W - fonts.regular.widthOfTextAtSize(bottom, 8)) / 2,
    y: 16,
    size: 8, font: fonts.regular, color: C.faint,
  })
}

// ─── Legal notice page ────────────────────────────────────────────────────────

function buildLegalPage(doc: PDFDocument, pages: PDFPage[], fonts: Fonts): void {
  const page = addContentPage(doc, pages)

  let y = CONTENT_TOP - 24
  page.drawText('Important Legal Notice', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 44

  y = drawSection(page, fonts, 'Legal Disclaimer', DISCLAIMER_BODY, y, C.warning)

  y = drawSection(
    page, fonts, 'Coverage Disclosure',
    'axe-core is an industry-standard automated accessibility testing tool developed by Deque Systems. ' +
    'Based on Deque\'s analysis of over 2,000 audits and 300,000 accessibility issues, automated tools ' +
    'identify approximately 57% of WCAG 2.2 Level AA issues. The remaining issues require manual review ' +
    'by a qualified accessibility specialist.',
    y, C.accent,
  )

  drawSection(
    page, fonts, 'Intended Use of This Document',
    'This report documents accessibility testing performed in good faith as part of a remediation effort. ' +
    'It demonstrates technical diligence and is intended to support an attorney\'s review of ' +
    'accessibility-related matters. It is not a certification, guarantee, or legal opinion.',
    y, C.navy,
  )
}

// ─── Executive summary ────────────────────────────────────────────────────────

function buildSummaryPage(doc: PDFDocument, pages: PDFPage[], fonts: Fonts, data: EvidenceData): void {
  const page = addContentPage(doc, pages)
  const sc = scoreColor(data.score)

  let y = CONTENT_TOP - 24
  page.drawText('Executive Summary', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 36

  // Score box — prominent, full width
  const boxH = 72
  drawRoundedRect(page, M, y, CW, boxH, 8, {
    color: dim(sc), borderColor: sc, borderWidth: 1,
  })
  const scoreStr = `${data.score} / 100`
  page.drawText(scoreStr, { x: M + 24, y: y - 48, size: 36, font: fonts.bold, color: sc })
  const sl = scoreLabel(data.score)
  page.drawText(sl, {
    x: W - M - 24 - fonts.bold.widthOfTextAtSize(sl, 14),
    y: y - 42,
    size: 14, font: fonts.bold, color: sc,
  })
  y -= boxH + 28

  // Stats table — alternating rows
  const rows: Array<{ label: string; value: string; color?: PdfColor }> = [
    { label: 'Total violations found',  value: String(data.violations.length) },
    { label: 'Critical violations',     value: String(data.violations.filter(v => v.impact === 'critical').length), color: C.critical },
    { label: 'Serious violations',      value: String(data.violations.filter(v => v.impact === 'serious').length),  color: C.serious },
    { label: 'Moderate violations',     value: String(data.violations.filter(v => v.impact === 'moderate').length), color: C.moderate },
    { label: 'Minor violations',        value: String(data.violations.filter(v => v.impact === 'minor' || v.impact === null).length), color: C.minor },
    { label: 'Checks passed',           value: String(data.passCount), color: C.success },
    { label: 'Requires manual review',  value: String(data.incompleteCount) },
  ]

  const ROW_H = 26
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i]!
    if (i % 2 === 0) {
      page.drawRectangle({ x: M, y: y - ROW_H + 8, width: CW, height: ROW_H, color: C.bgPage })
    }
    page.drawText(r.label, { x: M + 12, y, size: 11, font: fonts.regular, color: C.muted })
    page.drawText(r.value, { x: M + 300, y, size: 12, font: fonts.bold, color: r.color ?? C.textDark })
    y -= ROW_H
  }

  y -= 24

  y = drawSection(
    page, fonts, 'Scan Scope',
    'This scan tested against WCAG 2.2 Level A and Level AA success criteria using axe-core ' +
    'rulesets wcag2a, wcag2aa, wcag21aa, and wcag22aa. Automated testing identifies approximately ' +
    '57% of applicable issues — manual review is required for complete coverage.',
    y, C.accent,
  )

  drawSection(
    page, fonts, 'Remediation Priority',
    'Address Critical violations first — they prevent some users from accessing content entirely. ' +
    'Then address Serious, Moderate, and Minor violations in order. Each violation in this report ' +
    'includes the WCAG criterion to help guide the remediation.',
    y, C.critical,
  )
}

// ─── Violations detail ────────────────────────────────────────────────────────

const DIFF_COLOR: Record<string, PdfColor> = {
  Easy: C.success, Medium: C.warning, Hard: C.danger,
}

function buildViolationPages(doc: PDFDocument, pages: PDFPage[], fonts: Fonts, data: EvidenceData): void {
  const shown   = data.violations.slice(0, 20)
  const hasMore = data.violations.length > 20

  const enhancedMap = new Map<string, EnhancedViolation>()
  for (const ev of data.enhancedViolations ?? []) {
    enhancedMap.set(ev.originalId, ev)
  }

  let page = addContentPage(doc, pages)
  let y    = CONTENT_TOP - 24
  page.drawText('Violations Detail', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 36

  // No violations — success state (checkmark drawn with lines; WinAnsi has no U+2713)
  if (shown.length === 0) {
    const boxH = 140
    drawRoundedRect(page, M, y, CW, boxH, 8, {
      color: dim(C.success), borderColor: C.success, borderWidth: 1,
    })
    const cx = W / 2
    const cy = y - 42
    page.drawLine({
      start: { x: cx - 14, y: cy }, end: { x: cx - 4, y: cy - 10 },
      thickness: 4, color: C.success, lineCap: LineCapStyle.Round,
    })
    page.drawLine({
      start: { x: cx - 4, y: cy - 10 }, end: { x: cx + 16, y: cy + 12 },
      thickness: 4, color: C.success, lineCap: LineCapStyle.Round,
    })
    const t1 = 'No Violations Detected'
    page.drawText(t1, {
      x: cx - fonts.bold.widthOfTextAtSize(t1, 16) / 2, y: y - 84,
      size: 16, font: fonts.bold, color: C.success,
    })
    const t2 = 'The automated scan found no WCAG violations. Manual testing is still recommended.'
    page.drawText(t2, {
      x: cx - fonts.regular.widthOfTextAtSize(t2, 10) / 2, y: y - 106,
      size: 10, font: fonts.regular, color: C.textMid,
    })
    return
  }

  const HEADER_H = 44
  const PAD      = 16
  const innerW   = CW - PAD * 2

  for (const v of shown) {
    const enhanced = enhancedMap.get(v.id)
    const iColor   = impactColor(v.impact)
    const impact   = (v.impact ?? 'minor').toUpperCase()

    const titleLines = wrapText(v.description, fonts.bold, 13, innerW)
    const wcagLine   = v.wcag_criteria.length > 0
      ? truncate(`WCAG: ${v.wcag_criteria.join(', ')}`, fonts.mono, 10, innerW)
      : null

    const peLines = enhanced ? wrapText(enhanced.plainEnglish,   fonts.italic,  12, innerW - 32) : []
    const biLines = enhanced ? wrapText(enhanced.businessImpact, fonts.regular, 12, innerW - 32) : []
    const peBoxH  = peLines.length > 0 ? 34 + peLines.length * 16 : 0
    const biBoxH  = biLines.length > 0 ? 34 + biLines.length * 16 : 0
    const diffH   = enhanced ? 30 : 0

    const bodyH = PAD + titleLines.length * 17 + (wcagLine ? 16 : 0) +
      (peBoxH ? peBoxH + 12 : 0) + (biBoxH ? biBoxH + 10 : 0) + diffH + PAD
    const cardH = HEADER_H + bodyH

    // Page break
    if (y - cardH < CONTENT_BOTTOM) {
      page = addContentPage(doc, pages)
      y = CONTENT_TOP - 8
    }

    // Card container
    drawRoundedRect(page, M, y, CW, cardH, 8, {
      color: C.white, borderColor: C.border, borderWidth: 1,
    })

    // Header strip (rounded top corners only) + bottom rule in severity color
    page.drawSvgPath(svgRoundedRectTop(CW, HEADER_H, 8), { x: M, y, color: dim(iColor) })
    page.drawLine({
      start: { x: M, y: y - HEADER_H }, end: { x: M + CW, y: y - HEADER_H },
      thickness: 1, color: iColor,
    })

    // Severity pill
    const pillW = fonts.bold.widthOfTextAtSize(impact, 9) + 24
    drawPill(page, M + PAD, y - 13, pillW, 18, iColor)
    page.drawText(impact, { x: M + PAD + 12, y: y - 26, size: 9, font: fonts.bold, color: C.white })

    // Violation id (center-ish) + elements affected (right)
    page.drawText(v.id, {
      x: M + PAD + pillW + 14, y: y - 26, size: 10, font: fonts.mono, color: C.muted,
    })
    const affected = `${v.nodes_affected} element${v.nodes_affected !== 1 ? 's' : ''} affected`
    page.drawText(affected, {
      x: M + CW - PAD - fonts.regular.widthOfTextAtSize(affected, 10),
      y: y - 26, size: 10, font: fonts.regular, color: C.muted,
    })

    // Body
    let by = y - HEADER_H - PAD - 10
    for (const line of titleLines) {
      page.drawText(line, { x: M + PAD, y: by, size: 13, font: fonts.bold, color: C.textDark })
      by -= 17
    }
    if (wcagLine) {
      page.drawText(wcagLine, { x: M + PAD, y: by, size: 10, font: fonts.mono, color: C.muted })
      by -= 16
    }

    // Plain English box (amber)
    if (peLines.length > 0) {
      by -= 6
      const boxTop = by + 10
      page.drawRectangle({ x: M + PAD, y: boxTop - peBoxH, width: innerW, height: peBoxH, color: C.amberBg })
      page.drawRectangle({ x: M + PAD, y: boxTop - peBoxH, width: 3, height: peBoxH, color: C.warning })
      page.drawText('PLAIN ENGLISH', {
        x: M + PAD + 16, y: boxTop - 16, size: 9, font: fonts.bold, color: C.amberFg,
      })
      let py = boxTop - 32
      for (const line of peLines) {
        page.drawText(line, { x: M + PAD + 16, y: py, size: 12, font: fonts.italic, color: C.amberTxt })
        py -= 16
      }
      by = boxTop - peBoxH - 6
    }

    // Legal relevance box (blue)
    if (biLines.length > 0) {
      by -= 4
      const boxTop = by + 10
      page.drawRectangle({ x: M + PAD, y: boxTop - biBoxH, width: innerW, height: biBoxH, color: C.blueBg })
      page.drawRectangle({ x: M + PAD, y: boxTop - biBoxH, width: 3, height: biBoxH, color: C.accent })
      page.drawText('LEGAL RELEVANCE', {
        x: M + PAD + 16, y: boxTop - 16, size: 9, font: fonts.bold, color: C.blueFg,
      })
      let ly = boxTop - 32
      for (const line of biLines) {
        page.drawText(line, { x: M + PAD + 16, y: ly, size: 12, font: fonts.regular, color: C.blueTxt })
        ly -= 16
      }
      by = boxTop - biBoxH - 6
    }

    // Fix difficulty + estimated time
    if (enhanced) {
      by -= 4
      const dc = DIFF_COLOR[enhanced.fixDifficulty] ?? C.muted
      page.drawText('Fix Difficulty:', { x: M + PAD, y: by - 6, size: 10, font: fonts.regular, color: C.muted })
      const dLabel = enhanced.fixDifficulty
      const labelX = M + PAD + fonts.regular.widthOfTextAtSize('Fix Difficulty:', 10) + 8
      const dW = fonts.bold.widthOfTextAtSize(dLabel, 9) + 20
      drawPill(page, labelX, by + 6, dW, 16, dc)
      page.drawText(dLabel, { x: labelX + 10, y: by - 5.5, size: 9, font: fonts.bold, color: C.white })
      const tLabel = `Estimated Time: ${enhanced.estimatedTime}`
      page.drawText(tLabel, {
        x: labelX + dW + 16, y: by - 6, size: 10, font: fonts.regular, color: C.textMid,
      })
    }

    y -= cardH + 20
  }

  if (hasMore) {
    if (y < CONTENT_BOTTOM + 20) {
      page = addContentPage(doc, pages)
      y = CONTENT_TOP - 8
    }
    page.drawText(
      `+ ${data.violations.length - 20} additional violations not shown. Remediate the issues above first.`,
      { x: M, y, size: 9, font: fonts.regular, color: C.muted },
    )
  }
}

// ─── Developer remediation guide ──────────────────────────────────────────────

function buildDevGuidePages(doc: PDFDocument, pages: PDFPage[], fonts: Fonts, data: EvidenceData): void {
  // Intro page
  const intro = addContentPage(doc, pages)

  let y = CONTENT_TOP - 24
  intro.drawText('Developer Remediation Guide', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 44

  y = drawSection(
    intro, fonts, 'About This Guide',
    'This guide lists the top WCAG accessibility violations found on your site and provides ' +
    'concrete code examples showing the issue (Before) and the fix (After). Examples are ' +
    'representative patterns — adapt them to match your specific implementation.',
    y, C.accent,
  )

  drawSection(
    intro, fonts, 'How to Use This Guide',
    'Work through violations in order from Critical to Minor. Each entry shows the WCAG criterion, ' +
    'estimated fix effort, and example code. After applying fixes, re-run the scan to verify improvements. ' +
    'Not all fixes require code changes — some may need CMS content updates or image edits.',
    y, C.accent,
  )

  // Disclaimer page required in every document
  buildLegalPage(doc, pages, fonts)

  // Sort by impact, take top 10
  const order = ['critical', 'serious', 'moderate', 'minor']
  const top10 = [...data.violations]
    .sort((a, b) => order.indexOf(a.impact ?? 'minor') - order.indexOf(b.impact ?? 'minor'))
    .slice(0, 10)

  let page = addContentPage(doc, pages)
  y = CONTENT_TOP - 24
  page.drawText('Remediation Instructions', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 40

  const bgBad  = rgb(0.996, 0.949, 0.949)  // #fef2f2
  const bgGood = rgb(0.941, 0.992, 0.957)  // #f0fdf4

  for (const v of top10) {
    const hint = HINTS[v.id] ?? FALLBACK_HINT

    const badLines      = hint.bad.split('\n')
    const goodLines     = hint.good.split('\n')
    const descLines     = wrapText(v.description, fonts.bold, 11, CW - 20)
    const guidanceLines = wrapText(hint.guidance, fonts.regular, 10, CW - 20)

    const neededH =
      26 +
      descLines.length * 15 +
      (v.wcag_criteria.length > 0 ? 15 : 0) +
      18 +
      guidanceLines.length * 14 +
      18 + badLines.length * 12 + 14 +
      18 + goodLines.length * 12 + 28

    if (y - neededH < CONTENT_BOTTOM) {
      page = addContentPage(doc, pages)
      y = CONTENT_TOP - 8
    }

    const iColor = impactColor(v.impact)
    const impact = (v.impact ?? 'minor').toUpperCase()

    // Severity pill + violation id
    const pillW = fonts.bold.widthOfTextAtSize(impact, 9) + 24
    drawPill(page, M, y + 4, pillW, 18, iColor)
    page.drawText(impact, { x: M + 12, y: y - 9, size: 9, font: fonts.bold, color: C.white })
    page.drawText(v.id, { x: M + pillW + 10, y: y - 9, size: 10, font: fonts.mono, color: C.muted })
    y -= 26

    for (const line of descLines) {
      page.drawText(line, { x: M + 10, y, size: 11, font: fonts.bold, color: C.textDark })
      y -= 15
    }

    if (v.wcag_criteria.length > 0) {
      page.drawText(truncate(`WCAG: ${v.wcag_criteria.join(', ')}`, fonts.mono, 9, CW - 20), {
        x: M + 10, y, size: 9, font: fonts.mono, color: C.muted,
      })
      y -= 15
    }

    const diffColor =
      hint.difficulty === 'Low'  ? C.success :
      hint.difficulty === 'High' ? C.danger : C.warning
    page.drawText(`Fix effort: ${hint.difficulty}`, {
      x: M + 10, y, size: 10, font: fonts.bold, color: diffColor,
    })
    y -= 18

    for (const line of guidanceLines) {
      page.drawText(line, { x: M + 10, y, size: 10, font: fonts.regular, color: C.textMid })
      y -= 14
    }
    y -= 4

    // Before block
    page.drawText('Before (issue present):', { x: M + 10, y, size: 9, font: fonts.bold, color: C.danger })
    y -= 13
    const badBoxH = badLines.length * 12 + 10
    page.drawRectangle({ x: M + 10, y: y - badBoxH + 9, width: CW - 20, height: badBoxH, color: bgBad })
    page.drawRectangle({ x: M + 10, y: y - badBoxH + 9, width: 3, height: badBoxH, color: C.danger })
    y -= 3
    for (const line of badLines) {
      page.drawText(line, { x: M + 20, y, size: 8, font: fonts.mono, color: C.textDark })
      y -= 12
    }
    y -= 8

    // After block
    page.drawText('After (accessible):', { x: M + 10, y, size: 9, font: fonts.bold, color: C.success })
    y -= 13
    const goodBoxH = goodLines.length * 12 + 10
    page.drawRectangle({ x: M + 10, y: y - goodBoxH + 9, width: CW - 20, height: goodBoxH, color: bgGood })
    page.drawRectangle({ x: M + 10, y: y - goodBoxH + 9, width: 3, height: goodBoxH, color: C.success })
    y -= 3
    for (const line of goodLines) {
      page.drawText(line, { x: M + 20, y, size: 8, font: fonts.mono, color: C.textDark })
      y -= 12
    }
    y -= 26
  }
}

// ─── Monitoring confirmation ──────────────────────────────────────────────────

function buildMonitoringPage(doc: PDFDocument, pages: PDFPage[], fonts: Fonts, data: MonitoringData): void {
  const page = addContentPage(doc, pages)

  let y = CONTENT_TOP - 24
  page.drawText('Monitoring Confirmation', { x: M, y, size: 24, font: fonts.bold, color: C.navy })
  y -= 40

  // Green status banner
  const bannerH = 68
  drawRoundedRect(page, M, y, CW, bannerH, 8, {
    color: dim(C.success), borderColor: C.success, borderWidth: 1,
  })
  page.drawText('ACTIVE', { x: M + 20, y: y - 30, size: 22, font: fonts.bold, color: C.success })
  page.drawText('Monthly accessibility scans are now scheduled for your website.', {
    x: M + 20, y: y - 52, size: 10, font: fonts.regular, color: C.textMid,
  })
  y -= bannerH + 28

  // Details table (alternating rows)
  const details: Array<[string, string]> = [
    ['Website',         truncate(data.url, fonts.regular, 11, CW - 200)],
    ['Activation Date', fmtDate(data.activationDate)],
    ['Alert Email',     data.email],
    ['Scan Schedule',   '1st of each month'],
    ['Alert Threshold', 'Email alert when score drops below 70'],
    ['Standard',        'WCAG 2.2 Level AA (axe-core rulesets incl. wcag22aa)'],
  ]

  const ROW_H = 26
  for (let i = 0; i < details.length; i++) {
    const [label, value] = details[i]!
    if (i % 2 === 0) {
      page.drawRectangle({ x: M, y: y - ROW_H + 8, width: CW, height: ROW_H, color: C.bgPage })
    }
    page.drawText(label!, { x: M + 12,  y, size: 11, font: fonts.bold,    color: C.muted })
    page.drawText(value!, { x: M + 170, y, size: 11, font: fonts.regular, color: C.textDark })
    y -= ROW_H
  }

  y -= 28

  drawSection(page, fonts, 'Important Legal Notice', DISCLAIMER_BODY, y, C.warning)
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateEvidencePackage(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  const pages: PDFPage[] = []

  buildCoverPage(doc, pages, fonts, data)
  buildLegalPage(doc, pages, fonts)
  buildSummaryPage(doc, pages, fonts, data)
  buildViolationPages(doc, pages, fonts, data)

  // Cover draws its own chrome — skip it
  applyChrome(pages, fonts, 'WCAG Technical Evidence Package', data.scanDate, true)
  return doc.save()
}

export async function generateDevGuide(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  const pages: PDFPage[] = []

  buildDevGuidePages(doc, pages, fonts, data)

  applyChrome(pages, fonts, 'Developer Remediation Guide', data.scanDate, false)
  return doc.save()
}

export async function generateMonitoringConfirmation(data: MonitoringData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  const pages: PDFPage[] = []

  buildMonitoringPage(doc, pages, fonts, data)

  applyChrome(pages, fonts, 'Monitoring Confirmation', data.activationDate, false)
  return doc.save()
}
