// Every PDF generated here MUST carry the legal disclaimer and ~57% axe-core coverage
// disclosure. CLAUDE.md Hard Rule 5 & 6 — enforced via DISCLAIMER_BODY constant below.
// FORBIDDEN language anywhere in this file: "ADA compliant", "lawsuit-proof", "certified accessible"

import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from 'pdf-lib'

// ─── Legal compliance constants ───────────────────────────────────────────────
const DISCLAIMER_BODY =
  'This document is not legal advice. It is a technical assessment generated by ' +
  'automated tooling. Consult a qualified attorney for legal guidance. This scan ' +
  'uses axe-core, which identifies approximately 57% of WCAG 2.1 accessibility ' +
  'issues per Deque Systems research. Manual testing is required for full ' +
  'compliance assessment.'

const FOOTER_NOTICE = 'Not legal advice  |  axe-core ~57% WCAG coverage  |  Consult a qualified attorney'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ViolationSummary {
  id: string
  description: string
  impact: 'critical' | 'serious' | 'moderate' | 'minor' | null
  nodes_affected: number
  wcag_criteria: string[]
}

export interface EnhancedViolation {
  originalId:     string
  plainEnglish:   string
  businessImpact: string
  fixDifficulty:  'Easy' | 'Medium' | 'Hard'
  estimatedTime:  string
}

export interface EvidenceData {
  url: string
  businessName?: string | null
  scanDate: Date
  score: number
  tier: 'basic' | 'premium' | 'monitoring'
  violations: ViolationSummary[]
  enhancedViolations?: EnhancedViolation[]
  passCount: number
  incompleteCount: number
}

export interface MonitoringData {
  url: string
  activationDate: Date
  email: string
}

// ─── Remediation hints (dev guide) ───────────────────────────────────────────

interface Hint {
  bad: string
  good: string
  difficulty: 'Low' | 'Medium' | 'High'
  guidance: string
}

const HINTS: Record<string, Hint> = {
  'color-contrast': {
    bad:  '<p style="color: #aaaaaa">Text content</p>',
    good: '<p style="color: #595959">Text content</p>',
    difficulty: 'Medium',
    guidance:
      'Ensure text has at least 4.5:1 contrast ratio against its background ' +
      '(3:1 for large text >= 18pt or 14pt bold). Use a contrast checker to verify your colors.',
  },
  'image-alt': {
    bad:  '<img src="banner.jpg">',
    good: '<img src="banner.jpg" alt="Describe the image content">',
    difficulty: 'Low',
    guidance:
      'Add a descriptive alt attribute to every <img> element. ' +
      'For purely decorative images use alt="" to signal screen readers should skip it.',
  },
  'label': {
    bad:  '<input type="text" name="email">',
    good: '<label for="email">Email address</label>\n<input type="text" id="email" name="email">',
    difficulty: 'Low',
    guidance:
      'Associate every form control with a visible label using matching for/id attributes. ' +
      'Alternatively use aria-label or aria-labelledby on the input.',
  },
  'heading-order': {
    bad:  '<h1>Page Title</h1>  ...  <h3>Section</h3>',
    good: '<h1>Page Title</h1>  ...  <h2>Section</h2>',
    difficulty: 'Low',
    guidance:
      'Heading levels must not skip. Use h1 -> h2 -> h3 in sequence. ' +
      'Never jump from h1 to h3 or h2 to h4.',
  },
  'link-name': {
    bad:  '<a href="/page"><img src="arrow.png"></a>',
    good: '<a href="/page"><img src="arrow.png" alt="View next page"></a>',
    difficulty: 'Low',
    guidance:
      'Every link must have discernible text: visible text content, ' +
      'aria-label, or descriptive alt text on a child image.',
  },
  'button-name': {
    bad:  '<button><img src="close.svg"></button>',
    good: '<button aria-label="Close dialog"><img src="close.svg" alt=""></button>',
    difficulty: 'Low',
    guidance:
      'Every button must have an accessible name via text content, aria-label, or aria-labelledby. ' +
      'Icon-only buttons always need aria-label.',
  },
  'html-has-lang': {
    bad:  '<html>',
    good: '<html lang="en">',
    difficulty: 'Low',
    guidance:
      'Add a lang attribute to the root <html> element using a valid BCP 47 ' +
      'language tag (en, fr, es, etc.).',
  },
  'document-title': {
    bad:  '<title></title>',
    good: '<title>Contact Us - My Business</title>',
    difficulty: 'Low',
    guidance:
      'Every page must have a non-empty, descriptive <title> element. ' +
      'Include both the page name and site name.',
  },
  'aria-required-attr': {
    bad:  '<div role="checkbox">Accept terms</div>',
    good: '<div role="checkbox" aria-checked="false" tabindex="0">Accept terms</div>',
    difficulty: 'Medium',
    guidance:
      'ARIA roles have required properties. The checkbox role requires aria-checked. ' +
      'Check the WAI-ARIA specification for each role\'s required attributes.',
  },
  'frame-title': {
    bad:  '<iframe src="map.html"></iframe>',
    good: '<iframe src="map.html" title="Store location map"></iframe>',
    difficulty: 'Low',
    guidance:
      'Add a descriptive title attribute to all <iframe> elements so screen reader ' +
      'users understand the frame\'s purpose.',
  },
}

const FALLBACK_HINT: Hint = {
  bad:  '<!-- Identify the failing element using browser DevTools -->\n<!-- Inspect for missing ARIA attributes or semantic HTML issues -->',
  good: '<!-- Apply the WCAG-compliant fix per the WAI-ARIA specification -->\n<!-- Test with a screen reader after making changes -->',
  difficulty: 'Medium',
  guidance:
    'Review the WAI-ARIA specification and WCAG 2.1 documentation for this criterion. ' +
    'Use browser accessibility DevTools to identify the affected elements and apply the recommended fix.',
}

// ─── Layout constants ─────────────────────────────────────────────────────────

const W             = 595.28
const H             = 841.89
const ML            = 50
const MR            = 50
const TW            = W - ML - MR   // 495.28
const MB            = 50
const COVER_BAND_H  = 252           // top 30% navy banner on cover page
const INNER_HEAD_H  = 36            // thin header bar on inner pages

// ─── Colors ───────────────────────────────────────────────────────────────────

const C = {
  navy:     rgb(0.102, 0.153, 0.267),  // #1a2744
  accent:   rgb(0.145, 0.388, 0.922),  // #2563eb
  dark:     rgb(0.067, 0.067, 0.067),
  muted:    rgb(0.420, 0.420, 0.420),
  light:    rgb(0.859, 0.859, 0.859),
  bg:       rgb(0.961, 0.965, 0.980),
  bgStripe: rgb(0.976, 0.980, 0.992),  // alternate row tint
  white:    rgb(1.000, 1.000, 1.000),
  critical: rgb(0.863, 0.149, 0.149),  // #dc2626
  serious:  rgb(0.918, 0.345, 0.047),  // #ea580c
  moderate: rgb(0.851, 0.467, 0.024),  // #d97706
  minor:    rgb(0.145, 0.388, 0.922),  // #2563eb
  green:    rgb(0.086, 0.639, 0.290),  // #16a34a
  bgAmber:  rgb(0.996, 0.953, 0.780),  // #fef3c7
  fgAmber:  rgb(0.573, 0.251, 0.055),  // #92400e
  bgCrit:   rgb(0.999, 0.941, 0.941),
  bgSer:    rgb(0.999, 0.965, 0.945),
  bgMod:    rgb(0.999, 0.980, 0.941),
  bgMin:    rgb(0.941, 0.957, 0.999),
  bgGreen:  rgb(0.929, 0.980, 0.941),
  headerSub:rgb(0.700, 0.780, 0.950),  // light blue-white for header sub-text
}

type PdfColor = ReturnType<typeof rgb>

// ─── Utilities ────────────────────────────────────────────────────────────────

function fmtDate(d: Date): string {
  return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
}

function scoreColor(score: number): PdfColor {
  if (score >= 80) return C.green
  if (score >= 60) return C.moderate
  return C.critical
}

function scoreLabel(score: number): string {
  if (score >= 80) return 'Good'
  if (score >= 60) return 'Needs Work'
  return 'Critical Issues'
}

function impactColor(impact: ViolationSummary['impact']): PdfColor {
  switch (impact) {
    case 'critical': return C.critical
    case 'serious':  return C.serious
    case 'moderate': return C.moderate
    case 'minor':    return C.minor
    default:         return C.muted
  }
}

function impactBg(impact: ViolationSummary['impact']): PdfColor {
  switch (impact) {
    case 'critical': return C.bgCrit
    case 'serious':  return C.bgSer
    case 'moderate': return C.bgMod
    case 'minor':    return C.bgMin
    default:         return C.bg
  }
}

function wrapText(text: string, font: PDFFont, size: number, maxWidth: number): string[] {
  const lines: string[] = []
  let current = ''
  for (const word of text.split(' ')) {
    const candidate = current ? `${current} ${word}` : word
    if (font.widthOfTextAtSize(candidate, size) <= maxWidth) {
      current = candidate
    } else {
      if (current) lines.push(current)
      current = word
    }
  }
  if (current) lines.push(current)
  return lines.length > 0 ? lines : ['']
}

interface Fonts { regular: PDFFont; bold: PDFFont; mono: PDFFont }

async function loadFonts(doc: PDFDocument): Promise<Fonts> {
  const [regular, bold, mono] = await Promise.all([
    doc.embedFont(StandardFonts.Helvetica),
    doc.embedFont(StandardFonts.HelveticaBold),
    doc.embedFont(StandardFonts.Courier),
  ])
  return { regular, bold, mono }
}

function drawWrapped(
  page: PDFPage,
  text: string,
  x: number,
  startY: number,
  font: PDFFont,
  size: number,
  color: PdfColor,
  maxWidth = TW,
  lineGap = 4,
): number {
  let y = startY
  for (const line of wrapText(text, font, size, maxWidth)) {
    page.drawText(line, { x, y, size, font, color })
    y -= size + lineGap
  }
  return y
}

function drawHRule(page: PDFPage, y: number, color: PdfColor = C.light): void {
  page.drawLine({ start: { x: ML, y }, end: { x: W - MR, y }, thickness: 0.5, color })
}

function drawFooter(page: PDFPage, fonts: Fonts, date: Date): void {
  const y = 28
  drawHRule(page, y + 14, C.light)
  page.drawText(
    `Generated ${fmtDate(date)}  |  ${FOOTER_NOTICE}`,
    { x: ML, y, size: 7, font: fonts.regular, color: C.muted },
  )
}

// Inner-page header: thin navy bar, section title left, doc name + page number right
function drawInnerHeader(
  page: PDFPage,
  fonts: Fonts,
  sectionTitle: string,
  pageNum: number,
  barColor: PdfColor = C.navy,
): void {
  page.drawRectangle({ x: 0, y: H - INNER_HEAD_H, width: W, height: INNER_HEAD_H, color: barColor })
  page.drawText(sectionTitle, { x: ML, y: H - 24, size: 12, font: fonts.bold, color: C.white })
  const right = `WCAG Technical Evidence Package  |  Page ${pageNum}`
  page.drawText(right, {
    x: W - MR - fonts.regular.widthOfTextAtSize(right, 7.5),
    y: H - 24,
    size: 7.5, font: fonts.regular, color: C.headerSub,
  })
}

// ─── Cover page ───────────────────────────────────────────────────────────────

function buildCoverPage(doc: PDFDocument, fonts: Fonts, data: EvidenceData): void {
  const page = doc.addPage([W, H])

  // ── Navy banner (top 30%) ────────────────────────────────────────────────────
  page.drawRectangle({ x: 0, y: H - COVER_BAND_H, width: W, height: COVER_BAND_H, color: C.navy })

  // Title
  page.drawText('WCAG Technical', { x: ML, y: H - 62, size: 30, font: fonts.bold, color: C.white })
  page.drawText('Evidence Package', { x: ML, y: H - 96, size: 30, font: fonts.bold, color: C.white })
  page.drawText('Accessibility Assessment Report', {
    x: ML, y: H - 120, size: 11, font: fonts.regular, color: C.headerSub,
  })

  // Business name + URL + date labels (left side of banner, below title)
  let infoY = H - 152
  if (data.businessName) {
    page.drawText('Business', { x: ML, y: infoY, size: 8, font: fonts.bold, color: C.headerSub })
    const bName = data.businessName.length > 46 ? `${data.businessName.slice(0, 43)}...` : data.businessName
    page.drawText(bName, { x: ML, y: infoY - 14, size: 10, font: fonts.bold, color: C.white })
    infoY -= 32
  }
  page.drawText('Scanned Website', { x: ML, y: infoY, size: 8, font: fonts.bold, color: C.headerSub })
  const displayUrl = data.url.length > 46 ? `${data.url.slice(0, 43)}...` : data.url
  page.drawText(displayUrl, { x: ML, y: infoY - 14, size: 10, font: fonts.bold, color: C.white })
  page.drawText('Scan Date', { x: ML, y: infoY - 34, size: 8, font: fonts.bold, color: C.headerSub })
  page.drawText(fmtDate(data.scanDate), { x: ML, y: infoY - 48, size: 10, font: fonts.regular, color: C.white })

  // ── Score circle (right side of banner) ─────────────────────────────────────
  const cx  = W - 105
  const cy  = H - 148
  const r   = 52
  const sc  = scoreColor(data.score)

  // Subtle outer ring
  page.drawEllipse({ x: cx, y: cy, xScale: r + 6, yScale: r + 6, color: rgb(1, 1, 1), opacity: 0.15 })
  // Filled circle
  page.drawEllipse({ x: cx, y: cy, xScale: r, yScale: r, color: sc })

  // Score number — centered
  const scoreStr = String(data.score)
  const scoreW   = fonts.bold.widthOfTextAtSize(scoreStr, 28)
  page.drawText(scoreStr, { x: cx - scoreW / 2, y: cy - 9, size: 28, font: fonts.bold, color: C.white })
  const subLabel = '/ 100'
  const subW     = fonts.regular.widthOfTextAtSize(subLabel, 9)
  page.drawText(subLabel, { x: cx - subW / 2, y: cy - 22, size: 9, font: fonts.regular, color: rgb(0.88, 0.88, 0.88) })

  // Score label below circle (inside banner)
  const sl  = scoreLabel(data.score)
  const slW = fonts.bold.widthOfTextAtSize(sl, 9)
  page.drawText(sl, { x: cx - slW / 2, y: cy - r - 14, size: 9, font: fonts.bold, color: C.headerSub })

  // ── Count boxes (just below banner) ─────────────────────────────────────────
  let y = H - COVER_BAND_H - 18

  const impacts: Array<{ label: string; color: PdfColor; count: number }> = [
    { label: 'Critical', color: C.critical, count: data.violations.filter(v => v.impact === 'critical').length },
    { label: 'Serious',  color: C.serious,  count: data.violations.filter(v => v.impact === 'serious').length },
    { label: 'Moderate', color: C.moderate, count: data.violations.filter(v => v.impact === 'moderate').length },
    { label: 'Minor',    color: C.minor,    count: data.violations.filter(v => v.impact === 'minor').length },
  ]

  const boxW = Math.floor((TW - 9) / 4)
  let bx = ML
  for (const item of impacts) {
    page.drawRectangle({ x: bx, y: y - 52, width: boxW, height: 60, color: C.bg })
    page.drawRectangle({ x: bx, y: y - 52, width: 4,    height: 60, color: item.color })
    page.drawText(String(item.count), { x: bx + 14, y: y - 18, size: 24, font: fonts.bold, color: item.color })
    page.drawText(item.label,         { x: bx + 14, y: y - 40, size: 9,  font: fonts.regular, color: C.muted })
    bx += boxW + 3
  }

  y -= 72

  // Stats line
  page.drawText(`${data.violations.length} violation type${data.violations.length !== 1 ? 's' : ''}`, {
    x: ML, y, size: 10, font: fonts.regular, color: C.dark,
  })
  page.drawText(`${data.passCount} checks passed`, {
    x: ML + 188, y, size: 10, font: fonts.regular, color: C.green,
  })
  page.drawText(`${data.incompleteCount} need manual review`, {
    x: ML + 340, y, size: 10, font: fonts.regular, color: C.muted,
  })
  y -= 24
  drawHRule(page, y)
  y -= 20

  // Tier badge
  const tierLabels: Record<string, string> = {
    basic:      'Basic — Evidence Package',
    premium:    'Premium — Evidence Package + Developer Guide',
    monitoring: 'Monitoring — Evidence Package + Monthly Scans',
  }
  const tierColors: Record<string, PdfColor> = {
    basic: C.accent, premium: rgb(0.42, 0.22, 0.68), monitoring: C.green,
  }
  const tLabel = tierLabels[data.tier] ?? data.tier
  const tColor = tierColors[data.tier] ?? C.accent
  const tW = fonts.bold.widthOfTextAtSize(tLabel, 9) + 20
  page.drawRectangle({ x: ML, y: y - 10, width: tW, height: 22, color: tColor })
  page.drawText(tLabel, { x: ML + 10, y: y - 3, size: 9, font: fonts.bold, color: C.white })

  y -= 38

  // Amber disclaimer note
  const noteLines = wrapText(
    'Note: Automated scanning detects approximately 57% of WCAG 2.1 issues per Deque Systems research. ' +
    'This package is a technical evidence document and does not constitute legal advice. ' +
    'Consult a qualified attorney for legal guidance.',
    fonts.regular, 9.5, TW - 24,
  )
  const noteH = noteLines.length * 13 + 16
  page.drawRectangle({ x: ML, y: y - noteH, width: TW,  height: noteH, color: C.bgAmber })
  page.drawRectangle({ x: ML, y: y - noteH, width: 4,   height: noteH, color: C.fgAmber })
  let ny = y - 9
  for (const line of noteLines) {
    page.drawText(line, { x: ML + 12, y: ny, size: 9.5, font: fonts.regular, color: C.fgAmber })
    ny -= 13
  }

  drawFooter(page, fonts, data.scanDate)
}

// ─── Legal notice page ────────────────────────────────────────────────────────

function buildDisclaimerPage(doc: PDFDocument, fonts: Fonts, date: Date, pageNum: number): void {
  const page = doc.addPage([W, H])
  drawInnerHeader(page, fonts, 'Important Legal Notice', pageNum)

  let y = H - INNER_HEAD_H - 32

  // Section 1 — Legal Disclaimer (amber box)
  const disclaimerLines = wrapText(DISCLAIMER_BODY, fonts.regular, 10.5, TW - 28)
  const dBoxH = disclaimerLines.length * 15 + 36
  page.drawRectangle({ x: ML,     y: y - dBoxH, width: TW, height: dBoxH, color: C.bgAmber })
  page.drawRectangle({ x: ML,     y: y - dBoxH, width: 4,  height: dBoxH, color: C.fgAmber })
  page.drawText('Legal Disclaimer', { x: ML + 14, y: y - 16, size: 12, font: fonts.bold, color: C.fgAmber })
  let dy = y - 34
  for (const line of disclaimerLines) {
    page.drawText(line, { x: ML + 14, y: dy, size: 10.5, font: fonts.regular, color: C.fgAmber })
    dy -= 15
  }

  y -= dBoxH + 24

  // Section 2 — Coverage Disclosure (blue-tinted box)
  const coverageText =
    'axe-core is an industry-standard automated accessibility testing tool developed by Deque Systems. ' +
    'Based on Deque\'s analysis of over 2,000 audits and 300,000 accessibility issues, automated tools ' +
    'identify approximately 57% of WCAG 2.1 Level AA issues. The remaining issues require manual review ' +
    'by a qualified accessibility specialist.'
  const covLines = wrapText(coverageText, fonts.regular, 10.5, TW - 28)
  const cBoxH = covLines.length * 15 + 36
  page.drawRectangle({ x: ML, y: y - cBoxH, width: TW, height: cBoxH, color: C.bgMin })
  page.drawRectangle({ x: ML, y: y - cBoxH, width: 4,  height: cBoxH, color: C.accent })
  page.drawText('Coverage Disclosure', { x: ML + 14, y: y - 16, size: 12, font: fonts.bold, color: C.navy })
  let cv = y - 34
  for (const line of covLines) {
    page.drawText(line, { x: ML + 14, y: cv, size: 10.5, font: fonts.regular, color: C.dark })
    cv -= 15
  }

  y -= cBoxH + 24

  // Section 3 — Intended Use (plain)
  page.drawText('Intended Use of This Document', { x: ML, y, size: 12, font: fonts.bold, color: C.dark })
  y -= 18
  drawWrapped(
    page,
    'This report documents accessibility testing performed in good faith as part of a remediation effort. ' +
    'It demonstrates technical diligence and is intended to support an attorney\'s review of ' +
    'accessibility-related matters. It is not a certification, guarantee, or legal opinion.',
    ML, y, fonts.regular, 10.5, C.dark, TW, 5,
  )

  drawFooter(page, fonts, date)
}

// ─── Executive summary ────────────────────────────────────────────────────────

function buildSummaryPage(doc: PDFDocument, fonts: Fonts, data: EvidenceData, pageNum: number): void {
  const page = doc.addPage([W, H])
  drawInnerHeader(page, fonts, 'Executive Summary', pageNum)

  let y = H - INNER_HEAD_H - 28

  // Score hero row
  const scoreLine = `${data.score} / 100`
  page.drawText('Accessibility Score', { x: ML, y, size: 12, font: fonts.bold, color: C.dark })
  page.drawText(scoreLine, {
    x: W - MR - fonts.bold.widthOfTextAtSize(scoreLine, 14),
    y, size: 14, font: fonts.bold, color: scoreColor(data.score),
  })
  y -= 14
  page.drawText(scoreLabel(data.score), { x: ML, y, size: 10, font: fonts.regular, color: scoreColor(data.score) })
  y -= 18
  drawHRule(page, y)
  y -= 16

  // Summary rows (alternating backgrounds)
  const rows: Array<{ label: string; value: string; color?: PdfColor; note?: string }> = [
    { label: 'Total violations found',  value: String(data.violations.length) },
    { label: 'Critical violations',     value: String(data.violations.filter(v => v.impact === 'critical').length), color: C.critical },
    { label: 'Serious violations',      value: String(data.violations.filter(v => v.impact === 'serious').length),  color: C.serious },
    { label: 'Moderate violations',     value: String(data.violations.filter(v => v.impact === 'moderate').length), color: C.moderate },
    { label: 'Minor violations',        value: String(data.violations.filter(v => v.impact === 'minor').length),    color: C.minor },
    { label: 'Checks passed',           value: String(data.passCount), color: C.green },
    { label: 'Requires manual review',  value: String(data.incompleteCount), note: '(automated tools cannot verify)' },
  ]

  const ROW_H = 22
  for (let i = 0; i < rows.length; i++) {
    const r = rows[i]!
    // Alternating row background
    if (i % 2 === 0) {
      page.drawRectangle({ x: ML - 4, y: y - ROW_H + 6, width: TW + 8, height: ROW_H, color: C.bgStripe })
    }
    page.drawText(r.label, { x: ML + 4, y, size: 10.5, font: fonts.regular, color: C.dark })
    page.drawText(r.value, {
      x: ML + 280, y, size: 10.5, font: fonts.bold, color: r.color ?? C.dark,
    })
    if (r.note) {
      page.drawText(r.note, { x: ML + 310, y, size: 8.5, font: fonts.regular, color: C.muted })
    }
    y -= ROW_H
  }

  y -= 16
  drawHRule(page, y)
  y -= 20

  // Scan scope section
  page.drawText('Scan Scope', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  // Left accent bar
  page.drawRectangle({ x: ML - 4, y: y - 52, width: 3, height: 62, color: C.accent })
  y -= 16
  y = drawWrapped(
    page,
    'This scan tested against WCAG 2.1 Level A and Level AA success criteria using axe-core rules: ' +
    'wcag2a, wcag2aa, wcag21aa. Automated testing identifies approximately 57% of applicable issues ' +
    '— manual review is required for complete coverage.',
    ML + 8, y, fonts.regular, 10, C.dark, TW - 8, 5,
  )

  y -= 20

  page.drawText('Remediation Priority', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  page.drawRectangle({ x: ML - 4, y: y - 64, width: 3, height: 74, color: C.critical })
  y -= 16
  drawWrapped(
    page,
    'Address Critical violations first — they prevent some users from accessing content entirely. ' +
    'Then address Serious, Moderate, and Minor violations in order. Each violation in this report ' +
    'includes the WCAG criterion to help guide the remediation.',
    ML + 8, y, fonts.regular, 10, C.dark, TW - 8, 5,
  )

  drawFooter(page, fonts, data.scanDate)
}

// ─── Violations detail ────────────────────────────────────────────────────────

function buildViolationPages(doc: PDFDocument, fonts: Fonts, data: EvidenceData, startPage: number): void {
  const shown   = data.violations.slice(0, 20)
  const hasMore = data.violations.length > 20

  // Build enhanced lookup map keyed by violation id
  const enhancedMap = new Map<string, EnhancedViolation>()
  for (const ev of data.enhancedViolations ?? []) {
    enhancedMap.set(ev.originalId, ev)
  }

  let pageNum = startPage
  let page    = doc.addPage([W, H])
  drawInnerHeader(page, fonts, 'Violations Detail', pageNum)
  let y            = H - INNER_HEAD_H - 22
  let firstOnPage  = true

  if (shown.length === 0) {
    // No-violations notice
    const noticeH = 60
    page.drawRectangle({ x: ML, y: y - noticeH, width: TW, height: noticeH, color: C.bgGreen })
    page.drawRectangle({ x: ML, y: y - noticeH, width: 4,  height: noticeH, color: C.green })
    page.drawText('No violations detected', { x: ML + 14, y: y - 18, size: 13, font: fonts.bold, color: C.green })
    page.drawText(
      'The automated scan found no WCAG violations. Manual testing is still recommended.',
      { x: ML + 14, y: y - 36, size: 10, font: fonts.regular, color: C.dark },
    )
    drawFooter(page, fonts, data.scanDate)
    return
  }

  for (let i = 0; i < shown.length; i++) {
    const v        = shown[i]!
    const enhanced = enhancedMap.get(v.id)
    const impact   = v.impact ?? 'minor'
    const iColor   = impactColor(v.impact)
    const iBg      = impactBg(v.impact)

    const descLines   = wrapText(v.description, fonts.regular, 10, TW - 22)
    const wcagLine    = v.wcag_criteria.length > 0

    // Calculate extra height for enhanced blocks
    const peLines  = enhanced ? wrapText(enhanced.plainEnglish,   fonts.regular, 9.5, TW - 36) : []
    const biLines  = enhanced ? wrapText(enhanced.businessImpact, fonts.regular, 9.5, TW - 36) : []
    const peH      = peLines.length  > 0 ? peLines.length  * 13 + 22 : 0
    const biH      = biLines.length  > 0 ? biLines.length  * 13 + 22 : 0
    const diffH    = enhanced ? 22 : 0

    const cardH = 16 + peH + biH + diffH + descLines.length * 14 + (wcagLine ? 14 : 0) + 14 + 16

    if (!firstOnPage && y - cardH < MB + 40) {
      drawFooter(page, fonts, data.scanDate)
      page = doc.addPage([W, H])
      pageNum++
      drawInnerHeader(page, fonts, 'Violations Detail (continued)', pageNum)
      y = H - INNER_HEAD_H - 22
    }
    firstOnPage = false

    // Card background + left border
    page.drawRectangle({ x: ML,     y: y - cardH, width: TW, height: cardH, color: iBg })
    page.drawRectangle({ x: ML,     y: y - cardH, width: 4,  height: cardH, color: iColor })

    // Severity badge (pill) + violation id — inside card
    const badgeLabel = impact.toUpperCase()
    const badgeW     = fonts.bold.widthOfTextAtSize(badgeLabel, 7.5) + 12
    page.drawRectangle({ x: ML + 12, y: y - 14, width: badgeW, height: 16, color: iColor })
    page.drawText(badgeLabel, { x: ML + 18, y: y - 10, size: 7.5, font: fonts.bold, color: C.white })
    page.drawText(v.id, { x: ML + badgeW + 18, y: y - 10, size: 9, font: fonts.mono, color: C.dark })

    // "N elements affected" right-aligned
    const affectedStr = `${v.nodes_affected} element${v.nodes_affected !== 1 ? 's' : ''} affected`
    page.drawText(affectedStr, {
      x: W - MR - fonts.regular.widthOfTextAtSize(affectedStr, 9),
      y: y - 10, size: 9, font: fonts.regular, color: C.muted,
    })

    y -= 22

    // Plain English box (amber) — from Claude enhancement
    if (peLines.length > 0) {
      page.drawRectangle({ x: ML + 12, y: y - peH, width: TW - 20, height: peH, color: C.bgAmber })
      page.drawText('What this means:', { x: ML + 20, y: y - 13, size: 8.5, font: fonts.bold, color: C.fgAmber })
      let py = y - 26
      for (const line of peLines) {
        page.drawText(line, { x: ML + 20, y: py, size: 9.5, font: fonts.regular, color: C.fgAmber })
        py -= 13
      }
      y -= peH + 4
    }

    // Business impact box (blue) — from Claude enhancement
    if (biLines.length > 0) {
      page.drawRectangle({ x: ML + 12, y: y - biH, width: TW - 20, height: biH, color: C.bgMin })
      page.drawText('Why this matters:', { x: ML + 20, y: y - 13, size: 8.5, font: fonts.bold, color: C.navy })
      let by = y - 26
      for (const line of biLines) {
        page.drawText(line, { x: ML + 20, y: by, size: 9.5, font: fonts.regular, color: C.dark })
        by -= 13
      }
      y -= biH + 4
    }

    // Fix difficulty badge
    if (enhanced) {
      const diffColors: Record<string, PdfColor> = { Easy: C.green, Medium: C.moderate, Hard: C.critical }
      const dc = diffColors[enhanced.fixDifficulty] ?? C.muted
      const diffLabel = `${enhanced.fixDifficulty} fix  ·  ${enhanced.estimatedTime}`
      const diffW     = fonts.bold.widthOfTextAtSize(diffLabel, 8) + 14
      page.drawRectangle({ x: ML + 12, y: y - 16, width: diffW, height: 18, color: dc, opacity: 0.15 })
      page.drawText(diffLabel, { x: ML + 19, y: y - 11, size: 8, font: fonts.bold, color: dc })
      y -= 22
    }

    // Technical description
    for (const line of descLines) {
      page.drawText(line, { x: ML + 12, y, size: 10, font: fonts.regular, color: C.dark })
      y -= 14
    }

    // WCAG criteria
    if (wcagLine) {
      page.drawText(`WCAG: ${v.wcag_criteria.join(', ')}`, {
        x: ML + 12, y, size: 8.5, font: fonts.regular, color: C.muted,
      })
      y -= 14
    }

    y -= 18  // card bottom padding + gap
  }

  if (hasMore) {
    y -= 4
    page.drawText(
      `+ ${data.violations.length - 20} additional violations not shown. Remediate the issues above first.`,
      { x: ML, y, size: 9, font: fonts.regular, color: C.muted },
    )
  }

  drawFooter(page, fonts, data.scanDate)
}

// ─── Developer remediation guide ──────────────────────────────────────────────

function buildDevGuidePages(doc: PDFDocument, fonts: Fonts, data: EvidenceData, startPage: number): void {
  const purple = rgb(0.42, 0.22, 0.68)

  // Guide intro page
  let pageNum = startPage
  const intro  = doc.addPage([W, H])
  drawInnerHeader(intro, fonts, 'Developer Remediation Guide', pageNum, purple)

  let y = H - INNER_HEAD_H - 32
  intro.drawText('About This Guide', { x: ML, y, size: 13, font: fonts.bold, color: C.dark })
  intro.drawRectangle({ x: ML - 4, y: y - 56, width: 3, height: 66, color: purple })
  y -= 18
  y = drawWrapped(
    intro,
    'This guide lists the top WCAG accessibility violations found on your site and provides ' +
    'concrete code examples showing the issue (Before) and the fix (After). Examples are ' +
    'representative patterns — adapt them to match your specific implementation.',
    ML + 8, y, fonts.regular, 11, C.dark, TW - 8, 5,
  )

  y -= 24
  intro.drawText('How to Use This Guide', { x: ML, y, size: 13, font: fonts.bold, color: C.dark })
  intro.drawRectangle({ x: ML - 4, y: y - 70, width: 3, height: 80, color: purple })
  y -= 18
  drawWrapped(
    intro,
    'Work through violations in order from Critical to Minor. Each entry shows the WCAG criterion, ' +
    'estimated fix effort, and example code. After applying fixes, re-run the scan to verify improvements. ' +
    'Not all fixes require code changes — some may need CMS content updates or image edits.',
    ML + 8, y, fonts.regular, 11, C.dark, TW - 8, 5,
  )

  drawFooter(intro, fonts, data.scanDate)

  // Disclaimer page required in every document
  pageNum++
  buildDisclaimerPage(doc, fonts, data.scanDate, pageNum)

  // Sort by impact, take top 10
  const order = ['critical', 'serious', 'moderate', 'minor']
  const top10 = [...data.violations]
    .sort((a, b) => order.indexOf(a.impact ?? 'minor') - order.indexOf(b.impact ?? 'minor'))
    .slice(0, 10)

  pageNum++
  let page = doc.addPage([W, H])
  drawInnerHeader(page, fonts, 'Remediation Instructions', pageNum, purple)
  y = H - INNER_HEAD_H - 22
  let firstOnPage = true

  for (let i = 0; i < top10.length; i++) {
    const v    = top10[i]!
    const hint = HINTS[v.id] ?? FALLBACK_HINT

    const badLines      = hint.bad.split('\n')
    const goodLines     = hint.good.split('\n')
    const descLines     = wrapText(v.description, fonts.regular, 10, TW - 20)
    const guidanceLines = wrapText(hint.guidance, fonts.regular, 9.5, TW - 20)

    const neededH =
      22 +                              // badge row
      descLines.length * 14 +
      (v.wcag_criteria.length > 0 ? 14 : 0) +
      14 +                              // difficulty
      guidanceLines.length * 14 +
      14 + badLines.length * 12 + 8 +   // before block
      14 + goodLines.length * 12 + 24   // after block + gap

    if (!firstOnPage && y - neededH < MB + 40) {
      drawFooter(page, fonts, data.scanDate)
      page = doc.addPage([W, H])
      pageNum++
      drawInnerHeader(page, fonts, 'Remediation Instructions (continued)', pageNum, purple)
      y = H - INNER_HEAD_H - 22
    }
    firstOnPage = false

    const iColor     = impactColor(v.impact)
    const impact     = v.impact ?? 'minor'
    const badgeLabel = impact.toUpperCase()
    const badgeW     = fonts.bold.widthOfTextAtSize(badgeLabel, 7.5) + 12

    // Badge + id
    page.drawRectangle({ x: ML, y: y - 14, width: badgeW, height: 16, color: iColor })
    page.drawText(badgeLabel, { x: ML + 6,          y: y - 10, size: 7.5, font: fonts.bold,    color: C.white })
    page.drawText(v.id,       { x: ML + badgeW + 8, y: y - 10, size: 9,   font: fonts.mono,    color: C.dark })
    y -= 22

    // Description
    for (const line of descLines) {
      page.drawText(line, { x: ML + 10, y, size: 10, font: fonts.regular, color: C.dark })
      y -= 14
    }

    // WCAG criteria
    if (v.wcag_criteria.length > 0) {
      page.drawText(`WCAG: ${v.wcag_criteria.join(', ')}`, {
        x: ML + 10, y, size: 8.5, font: fonts.regular, color: C.muted,
      })
      y -= 14
    }

    // Fix effort
    const diffColor =
      hint.difficulty === 'Low'  ? C.green :
      hint.difficulty === 'High' ? C.critical : C.serious
    page.drawText(`Fix effort: ${hint.difficulty}`, {
      x: ML + 10, y, size: 9, font: fonts.bold, color: diffColor,
    })
    y -= 14

    // Guidance
    for (const line of guidanceLines) {
      page.drawText(line, { x: ML + 10, y, size: 9.5, font: fonts.regular, color: C.muted })
      y -= 14
    }
    y -= 6

    // Before block
    page.drawText('Before (issue present):', { x: ML + 10, y, size: 8.5, font: fonts.bold, color: C.critical })
    y -= 12
    const badBoxH = badLines.length * 12 + 8
    page.drawRectangle({ x: ML + 10, y: y - badBoxH, width: TW - 20, height: badBoxH, color: C.bgCrit })
    page.drawRectangle({ x: ML + 10, y: y - badBoxH, width: 3,       height: badBoxH, color: C.critical })
    y -= 5
    for (const line of badLines) {
      page.drawText(line, { x: ML + 18, y, size: 8, font: fonts.mono, color: C.dark })
      y -= 12
    }
    y -= 6

    // After block
    page.drawText('After (accessible):', { x: ML + 10, y, size: 8.5, font: fonts.bold, color: C.green })
    y -= 12
    const goodBoxH = goodLines.length * 12 + 8
    page.drawRectangle({ x: ML + 10, y: y - goodBoxH, width: TW - 20, height: goodBoxH, color: C.bgGreen })
    page.drawRectangle({ x: ML + 10, y: y - goodBoxH, width: 3,       height: goodBoxH, color: C.green })
    y -= 5
    for (const line of goodLines) {
      page.drawText(line, { x: ML + 18, y, size: 8, font: fonts.mono, color: C.dark })
      y -= 12
    }
    y -= 22
  }

  drawFooter(page, fonts, data.scanDate)
}

// ─── Monitoring confirmation ───────────────────────────────────────────────────

function buildMonitoringPage(doc: PDFDocument, fonts: Fonts, data: MonitoringData, pageNum: number): void {
  const page = doc.addPage([W, H])
  drawInnerHeader(page, fonts, 'Monitoring Activated', pageNum, C.green)

  let y = H - INNER_HEAD_H - 28

  // Green status banner
  const bannerH = 64
  page.drawRectangle({ x: ML, y: y - bannerH, width: TW, height: bannerH, color: C.bgGreen })
  page.drawRectangle({ x: ML, y: y - bannerH, width: 4,  height: bannerH, color: C.green })
  page.drawText('ACTIVE', { x: ML + 14, y: y - 18, size: 22, font: fonts.bold, color: C.green })
  page.drawText('Monthly accessibility scans are now scheduled for your website.', {
    x: ML + 14, y: y - 40, size: 10, font: fonts.regular, color: C.dark,
  })

  y -= bannerH + 24

  // Details table (alternating rows)
  const details: Array<[string, string]> = [
    ['Website',         data.url.length > 55 ? `${data.url.slice(0, 52)}...` : data.url],
    ['Activation Date', fmtDate(data.activationDate)],
    ['Alert Email',     data.email],
    ['Scan Schedule',   '1st of each month'],
    ['Alert Threshold', 'Email alert when score drops below 70'],
    ['Standard',        'WCAG 2.1 Level AA (wcag2a, wcag2aa, wcag21aa)'],
  ]

  const ROW_H = 24
  for (let i = 0; i < details.length; i++) {
    const [label, value] = details[i]!
    if (i % 2 === 0) {
      page.drawRectangle({ x: ML - 4, y: y - ROW_H + 8, width: TW + 8, height: ROW_H, color: C.bgStripe })
    }
    page.drawText(label!, { x: ML + 4, y,          size: 10, font: fonts.bold,    color: C.muted })
    page.drawText(value!, { x: ML + 160, y,         size: 10, font: fonts.regular, color: C.dark })
    y -= ROW_H
  }

  y -= 20
  drawHRule(page, y)
  y -= 20

  page.drawText('Important Legal Notice', { x: ML, y, size: 11, font: fonts.bold, color: C.dark })
  y -= 16
  drawWrapped(page, DISCLAIMER_BODY, ML, y, fonts.regular, 9.5, C.muted, TW, 4)

  drawFooter(page, fonts, data.activationDate)
}

// ─── Public API ───────────────────────────────────────────────────────────────

export async function generateEvidencePackage(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildCoverPage(doc, fonts, data)          // page 1
  buildDisclaimerPage(doc, fonts, data.scanDate, 2)  // page 2
  buildSummaryPage(doc, fonts, data, 3)     // page 3
  buildViolationPages(doc, fonts, data, 4)  // page 4+
  return doc.save()
}

export async function generateDevGuide(data: EvidenceData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildDevGuidePages(doc, fonts, data, 1)
  return doc.save()
}

export async function generateMonitoringConfirmation(data: MonitoringData): Promise<Uint8Array> {
  const doc   = await PDFDocument.create()
  const fonts = await loadFonts(doc)
  buildMonitoringPage(doc, fonts, data, 1)
  return doc.save()
}
