import { Resend } from 'resend'
import { createServiceClient } from '@saas/db'

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PdfDeliveryParams {
  paymentId: string
  email: string
  tier: 'basic' | 'premium' | 'monitoring'
  pdfUrls: string[]          // signed URLs in generation order
  scanScore: number
}

// ─── Constants ────────────────────────────────────────────────────────────────

const RESEND_DAILY_CAP   = 100
const RESEND_DAILY_WARN  = 95   // warn when ≥ this many sent today

const DISCLAIMER =
  'This is a technical assessment generated by automated tooling. It is not legal advice ' +
  'and does not constitute a legal compliance determination. Consult a qualified attorney ' +
  'regarding your specific situation. This scan uses axe-core, which identifies approximately ' +
  '57% of WCAG 2.1 accessibility issues per Deque Systems research. A complete accessibility ' +
  'audit requires manual review by a qualified accessibility specialist.'

const TIER_LABEL: Record<string, string> = {
  basic:      'Basic ($49)',
  premium:    'Premium ($79)',
  monitoring: 'Monitoring ($149/mo)',
}

const DOC_LABELS: Record<string, string> = {
  'evidence-package.pdf':        'WCAG Technical Evidence Package',
  'developer-guide.pdf':         'Developer Remediation Guide',
  'monitoring-confirmation.pdf': 'Monitoring Activation Confirmation',
}

const DOC_ORDER = [
  'evidence-package.pdf',
  'developer-guide.pdf',
  'monitoring-confirmation.pdf',
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

function scoreColor(score: number): string {
  if (score >= 80) return '#16a34a'   // green
  if (score >= 50) return '#d97706'   // amber
  return '#dc2626'                    // red
}

function buildHtml(params: PdfDeliveryParams, pdfFilenames: string[]): string {
  const { tier, pdfUrls, scanScore } = params

  const linkItems = pdfFilenames.map((filename, i) => {
    const url   = pdfUrls[i] ?? '#'
    const label = DOC_LABELS[filename] ?? filename
    return `
      <tr>
        <td style="padding:8px 0;">
          <a href="${url}"
             style="display:inline-block;background:#1d4ed8;color:#fff;text-decoration:none;
                    padding:10px 20px;border-radius:6px;font-size:14px;font-weight:600;">
            &#8595; Download ${label}
          </a>
          <span style="display:block;font-size:12px;color:#6b7280;margin-top:4px;">
            Link valid for 7 days
          </span>
        </td>
      </tr>`
  }).join('\n')

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Your WCAG Technical Evidence Package</title></head>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,Helvetica,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f3f4f6;padding:32px 16px;">
    <tr><td align="center">
      <table width="600" cellpadding="0" cellspacing="0"
             style="background:#fff;border-radius:8px;overflow:hidden;max-width:600px;width:100%;">

        <!-- Header -->
        <tr>
          <td style="background:#1d4ed8;padding:32px;text-align:center;">
            <h1 style="margin:0;color:#fff;font-size:22px;font-weight:700;">
              Your WCAG Technical Evidence Package is Ready
            </h1>
          </td>
        </tr>

        <!-- Body -->
        <tr>
          <td style="padding:32px;">

            <p style="margin:0 0 16px;color:#374151;font-size:15px;">
              Thank you for your purchase. Your documents for the
              <strong>${TIER_LABEL[tier] ?? tier}</strong> tier are available below.
              These links expire in <strong>7 days</strong>.
            </p>

            <!-- Score -->
            <div style="background:#f9fafb;border:1px solid #e5e7eb;border-radius:6px;
                        padding:16px 20px;margin:0 0 24px;text-align:center;">
              <div style="font-size:13px;color:#6b7280;margin-bottom:4px;">
                WCAG Automated Scan Score
              </div>
              <div style="font-size:42px;font-weight:700;color:${scoreColor(scanScore)};">
                ${scanScore}/100
              </div>
              <div style="font-size:12px;color:#9ca3af;margin-top:4px;">
                Based on axe-core automated scan (~57% WCAG coverage)
              </div>
            </div>

            <!-- Download links -->
            <h2 style="font-size:16px;color:#111827;margin:0 0 12px;">Download Your Documents</h2>
            <table cellpadding="0" cellspacing="0" width="100%">
              ${linkItems}
            </table>

            <!-- Coverage note -->
            <div style="background:#fffbeb;border:1px solid #fde68a;border-radius:6px;
                        padding:14px 16px;margin:28px 0 0;">
              <p style="margin:0;font-size:13px;color:#92400e;">
                <strong>Coverage Note:</strong> Automated scanning with axe-core identifies
                approximately 57% of WCAG 2.1 accessibility issues. The remaining issues require
                manual review by a qualified accessibility specialist.
              </p>
            </div>

          </td>
        </tr>

        <!-- Legal disclaimer -->
        <tr>
          <td style="background:#f9fafb;border-top:1px solid #e5e7eb;padding:24px 32px;">
            <p style="margin:0;font-size:11px;color:#6b7280;line-height:1.6;">
              <strong>Legal Disclaimer:</strong> ${DISCLAIMER}
            </p>
          </td>
        </tr>

      </table>
    </td></tr>
  </table>
</body>
</html>`
}

// ─── Daily cap check ──────────────────────────────────────────────────────────

async function getDailySentCount(): Promise<number> {
  const db    = createServiceClient()
  const today = new Date().toISOString().slice(0, 10)   // YYYY-MM-DD

  const { count } = await db
    .from('email_deliveries')
    .select('*', { count: 'exact', head: true })
    .eq('status', 'sent')
    .gte('sent_at', `${today}T00:00:00.000Z`)
    .lt('sent_at', `${today}T23:59:59.999Z`)

  return count ?? 0
}

// ─── Main export ──────────────────────────────────────────────────────────────

export async function sendPdfDelivery(params: PdfDeliveryParams): Promise<void> {
  const { paymentId, email, tier, pdfUrls } = params
  const db = createServiceClient()

  // Derive filenames by tier (same order as buildPdfsForTier)
  const pdfFilenames = DOC_ORDER.filter((_, i) => i < pdfUrls.length)

  try {
    // ── Daily cap guard ───────────────────────────────────────────────────────
    const dailyCount = await getDailySentCount()
    if (dailyCount >= RESEND_DAILY_CAP) {
      console.error(`Resend daily cap reached (${dailyCount}/${RESEND_DAILY_CAP}). Email NOT sent for payment ${paymentId}.`)
      await db
        .from('email_deliveries')
        .update({ status: 'failed' })
        .eq('payment_id', paymentId)
      return
    }
    if (dailyCount >= RESEND_DAILY_WARN) {
      console.warn(`Resend daily count at ${dailyCount}/${RESEND_DAILY_CAP} — approaching limit.`)
    }

    // ── Send via Resend ───────────────────────────────────────────────────────
    const resend = new Resend(process.env.RESEND_API_KEY)
    const fromEmail = process.env.RESEND_FROM_EMAIL ?? 'onboarding@resend.dev'

    const { error } = await resend.emails.send({
      from:    `ADA Evidence Tool <${fromEmail}>`,
      to:      email,
      subject: 'Your WCAG Technical Evidence Package is ready',
      html:    buildHtml(params, pdfFilenames),
    })

    if (error) {
      throw new Error(`Resend error: ${error.message}`)
    }

    // ── Mark as sent ──────────────────────────────────────────────────────────
    const { error: updateError } = await db
      .from('email_deliveries')
      .update({ status: 'sent', sent_at: new Date().toISOString() })
      .eq('payment_id', paymentId)

    if (updateError) {
      console.error('email_deliveries update to sent failed:', updateError)
    }

  } catch (err) {
    // Non-fatal: log and mark failed — caller (webhook) still returns 200
    console.error(`sendPdfDelivery failed for payment ${paymentId}:`, err)

    await db
      .from('email_deliveries')
      .update({ status: 'failed' })
      .eq('payment_id', paymentId)
      .then(({ error }) => {
        if (error) console.error('email_deliveries update to failed:', error)
      })
  }
}
